// lib/services.ts
// Updated with finalized single-tier pricing (Professional Consulting)
// Fee structure: Statutory Fee + Professional Fee (+ 18% GST on Prof Fee only)

import { SERVICE_FORM_CONFIGS } from './service-form-configs';

export interface Service {
  id: string;
  slug: string;
  name: string;
  description: string;
  category: string;
  categoryGroup: string;
  
  // Pricing (all in ₹)
  statutoryFee: number;      // Government fee (no GST)
  professionalFee: number;   // Our fee (before GST)
  gst: number;               // 18% of professional fee
  totalPayable: number;      // Total = statutory + professional + GST
  price: number;             // Alias for totalPayable (for compatibility)
  
  // Legacy fields for compatibility
  fee: string;               // For display: professional fee as string
  governmentFee: string;     // For display: statutory fee as string
  
  processingTime: string;
  requiredDocuments: string[];
  popular?: boolean;
  comingSoon?: boolean;
}

export const SERVICES: Service[] = [
  // ========================================
  // GROUP 1: STUDENT & EDUCATION SOLUTIONS
  // ========================================
  {
    id: 'REV-001',
    slug: 'community-certificate',
    name: 'Community Certificate',
    description: 'Official community certificate for educational benefits and government schemes.',
    category: 'certificates',
    categoryGroup: 'Student & Education Solutions',
    statutoryFee: 60,
    professionalFee: 340,
    gst: 61.20,
    totalPayable: 461.20,
    price: 461.20,
    fee: '340',
    governmentFee: '₹60',
    processingTime: '15-30 days',
    requiredDocuments: [
      'Identity Proof (Aadhaar, Passport, etc.)',
      'Address Proof',
      'Community Proof Documents',
      'School/College Certificate (if applicable)',
      'Parents Community Certificate (if available)'
    ],
    popular: true,
  },
  {
    id: 'REV-002',
    slug: 'income-certificate',
    name: 'Income Certificate',
    description: 'Income certificate for scholarships, educational loans, and fee concessions.',
    category: 'certificates',
    categoryGroup: 'Student & Education Solutions',
    statutoryFee: 60,
    professionalFee: 340,
    gst: 61.20,
    totalPayable: 461.20,
    price: 461.20,
    fee: '340',
    governmentFee: '₹60',
    processingTime: '15-30 days',
    requiredDocuments: [
      'Income Proof (Salary Slips, ITR, Form 16)',
      'Ration Card',
      'Property Documents (if applicable)',
      'Bank Statements (last 6 months)',
      'Self-Declaration Affidavit'
    ],
    popular: true,
  },
  {
    id: 'REV-003',
    slug: 'nativity-certificate',
    name: 'Nativity Certificate',
    description: 'Nativity certificate proving native status for educational and employment benefits.',
    category: 'certificates',
    categoryGroup: 'Student & Education Solutions',
    statutoryFee: 60,
    professionalFee: 340,
    gst: 61.20,
    totalPayable: 461.20,
    price: 461.20,
    fee: '340',
    governmentFee: '₹60',
    processingTime: '15-30 days',
    requiredDocuments: [
      'Birth Certificate',
      'School Certificates from state schools',
      'Address Proof (long-term residence)',
      'Parents Nativity Certificate (if available)',
      'Ration Card'
    ],
  },
  {
    id: 'REV-004',
    slug: 'first-graduate-certificate',
    name: 'First Graduate Certificate',
    description: 'Certificate for students who are first in their family to pursue higher education.',
    category: 'certificates',
    categoryGroup: 'Student & Education Solutions',
    statutoryFee: 60,
    professionalFee: 590,
    gst: 106.20,
    totalPayable: 756.20,
    price: 756.20,
    fee: '590',
    governmentFee: '₹60',
    processingTime: '30-45 days',
    requiredDocuments: [
      'Educational Certificates of Parents',
      'Family Details',
      'Ration Card',
      'Self-Declaration Affidavit',
      'Passport Size Photographs'
    ],
  },

  // ========================================
  // GROUP 2: PERSONAL & FAMILY SOLUTIONS
  // ========================================
  {
    id: 'REV-114',
    slug: 'legal-heir-certificate',
    name: 'Legal Heir Certificate',
    description: 'Official legal heir certificate for claiming assets, insurance, and inheritance rights.',
    category: 'legal',
    categoryGroup: 'Personal & Family Solutions',
    statutoryFee: 60,
    professionalFee: 1140,
    gst: 205.20,
    totalPayable: 1405.20,
    price: 1405.20,
    fee: '1140',
    governmentFee: '₹60',
    processingTime: '45-60 days',
    requiredDocuments: [
      'Death Certificate of Deceased',
      'Family Tree/Pedigree Chart',
      'Affidavits from Legal Heirs',
      'Witness Statements with Identity Proof',
      'Address Proof of all Legal Heirs',
      'Ration Card',
      'Property Documents (if applicable)'
    ],
    popular: true,
  },
  {
    id: 'CER-001',
    slug: 'birth-certificate',
    name: 'Birth Certificate (Print)',
    description: 'Official birth certificate print from municipal records.',
    category: 'certificates',
    categoryGroup: 'Personal & Family Solutions',
    statutoryFee: 20,
    professionalFee: 130,
    gst: 23.40,
    totalPayable: 173.40,
    price: 173.40,
    fee: '130',
    governmentFee: '₹20',
    processingTime: '7-15 days',
    requiredDocuments: [
      'Hospital Birth Report',
      'Parents Identity Proof',
      'Address Proof',
      'Existing Birth Certificate Number (if reprint)'
    ],
    popular: true,
  },
  {
    id: 'CER-002',
    slug: 'death-certificate',
    name: 'Death Certificate (Print)',
    description: 'Official death certificate print from municipal records.',
    category: 'certificates',
    categoryGroup: 'Personal & Family Solutions',
    statutoryFee: 20,
    professionalFee: 130,
    gst: 23.40,
    totalPayable: 173.40,
    price: 173.40,
    fee: '130',
    governmentFee: '₹20',
    processingTime: '7-15 days',
    requiredDocuments: [
      'Medical Certificate of Death',
      'Identity Proof of Deceased',
      'Applicant Identity Proof',
      'Existing Certificate Number (if reprint)'
    ],
  },
  {
    id: 'REV-201',
    slug: 'widow-certificate',
    name: 'Widow Certificate',
    description: 'Widow certificate for pension schemes and government benefits.',
    category: 'certificates',
    categoryGroup: 'Personal & Family Solutions',
    statutoryFee: 60,
    professionalFee: 390,
    gst: 70.20,
    totalPayable: 520.20,
    price: 520.20,
    fee: '390',
    governmentFee: '₹60',
    processingTime: '30-45 days',
    requiredDocuments: [
      'Death Certificate of Husband',
      'Marriage Certificate',
      'Identity Proof',
      'Address Proof',
      'Income Certificate'
    ],
  },
  {
    id: 'REV-202',
    slug: 'deserted-woman-certificate',
    name: 'Deserted Woman Certificate',
    description: 'Certificate for deserted women to access government welfare schemes.',
    category: 'certificates',
    categoryGroup: 'Personal & Family Solutions',
    statutoryFee: 60,
    professionalFee: 540,
    gst: 97.20,
    totalPayable: 697.20,
    price: 697.20,
    fee: '540',
    governmentFee: '₹60',
    processingTime: '45-60 days',
    requiredDocuments: [
      'Marriage Certificate',
      'Proof of Desertion (Police Complaint, etc.)',
      'Identity Proof',
      'Address Proof',
      'Income Certificate',
      'Witness Statements'
    ],
  },

  // ========================================
  // GROUP 3: PROPERTY & ASSET SOLUTIONS
  // ========================================
  {
    id: 'REV-301',
    slug: 'patta-transfer-full-field',
    name: 'Patta Transfer (Full Field)',
    description: 'Complete patta transfer for entire land parcel with revenue records update.',
    category: 'property',
    categoryGroup: 'Property & Asset Solutions',
    statutoryFee: 60,
    professionalFee: 840,
    gst: 151.20,
    totalPayable: 1051.20,
    price: 1051.20,
    fee: '840',
    governmentFee: '₹60',
    processingTime: '60-90 days',
    requiredDocuments: [
      'Registered Sale Deed',
      'Old Patta Copy',
      'Survey Documents (FMB, Chitta)',
      'Encumbrance Certificate',
      'Property Tax Receipts',
      'Identity Proof of Buyer'
    ],
    popular: true,
  },
  {
    id: 'REV-302',
    slug: 'patta-transfer-subdivision',
    name: 'Patta Transfer (Subdivision)',
    description: 'Patta transfer with land subdivision into multiple parcels.',
    category: 'property',
    categoryGroup: 'Property & Asset Solutions',
    statutoryFee: 60,
    professionalFee: 1440,
    gst: 259.20,
    totalPayable: 1759.20,
    price: 1759.20,
    fee: '1440',
    governmentFee: '₹60',
    processingTime: '90-120 days',
    requiredDocuments: [
      'Registered Sale Deed',
      'Old Patta Copy',
      'Survey Documents with Subdivision Plan',
      'Surveyor Certificate',
      'Encumbrance Certificate',
      'Property Tax Receipts',
      'NOC from Local Authority'
    ],
  },

  // ========================================
  // GROUP 4: BUSINESS & LICENSING SOLUTIONS
  // ========================================
  {
    id: 'COC-401',
    slug: 'trade-license',
    name: 'Trade License (Chennai)',
    description: 'Municipal trade license for legally operating business premises in Chennai.',
    category: 'business',
    categoryGroup: 'Business & Licensing Solutions',
    statutoryFee: 100,
    professionalFee: 1700,
    gst: 306,
    totalPayable: 2106,
    price: 2106,
    fee: '1700',
    governmentFee: '₹100 (minimum)',
    processingTime: '30-45 days',
    requiredDocuments: [
      'Property Documents (Ownership/Rent Agreement)',
      'Identity Proof of Business Owner',
      'Business Plan/Activity Details',
      'NOC from Property Owner',
      'Site Plan/Layout',
      'Partnership Deed (if applicable)',
      'Company Registration (if applicable)'
    ],
    popular: true,
  },
  {
    id: 'DFR-103',
    slug: 'fire-noc',
    name: 'Fire NOC (Non-Multi Storeyed Building)',
    description: 'Fire department NOC for commercial buildings and establishments.',
    category: 'business',
    categoryGroup: 'Business & Licensing Solutions',
    statutoryFee: 15,
    professionalFee: 4985,
    gst: 897.30,
    totalPayable: 5897.30,
    price: 5897.30,
    fee: '4985',
    governmentFee: '₹15',
    processingTime: '45-60 days',
    requiredDocuments: [
      'Building Plan (Approved by Municipal Corporation)',
      'Property Documents',
      'Fire Safety Equipment Details',
      'Site Plan with Fire Fighting Arrangements',
      'Building Usage Certificate',
      'Trade License',
      'Electrical Safety Certificate',
      'Water Storage Details'
    ],
    popular: true,
  },
  {
    id: 'REV-402',
    slug: 'money-lender-license',
    name: "Money Lender's License",
    description: 'Official license for conducting money lending business operations.',
    category: 'business',
    categoryGroup: 'Business & Licensing Solutions',
    statutoryFee: 60,
    professionalFee: 1940,
    gst: 349.20,
    totalPayable: 2349.20,
    price: 2349.20,
    fee: '1940',
    governmentFee: '₹60',
    processingTime: '60-90 days',
    requiredDocuments: [
      'Business Registration Documents',
      'Identity and Address Proof',
      'PAN Card',
      'Financial Statements',
      'Bank Account Details',
      'Character Certificate',
      'Property Documents (if applicable)'
    ],
  },

  // ========================================
  // GROUP 5: SOCIAL & PENSION SCHEMES
  // ========================================
  {
    id: 'REV-501',
    slug: 'old-age-pension',
    name: 'Old Age Pension (OAP)',
    description: 'Monthly pension scheme for senior citizens under government welfare programs.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 60,
    professionalFee: 439,
    gst: 79.02,
    totalPayable: 618.02,
    price: 618.02,
    fee: '439',
    governmentFee: '₹60',
    processingTime: '45-60 days',
    requiredDocuments: [
      'Age Proof (Birth Certificate, Aadhaar, etc.)',
      'Income Certificate',
      'Bank Account Details with Passbook Copy',
      'Aadhaar Card',
      'Recent Passport Size Photographs',
      'Ration Card'
    ],
    popular: true,
  },
  {
    id: 'REV-502',
    slug: 'widow-pension',
    name: 'Destitute Widow Pension',
    description: 'Monthly pension for widows below poverty line under state welfare schemes.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 60,
    professionalFee: 439,
    gst: 79.02,
    totalPayable: 618.02,
    price: 618.02,
    fee: '439',
    governmentFee: '₹60',
    processingTime: '45-60 days',
    requiredDocuments: [
      'Death Certificate of Husband',
      'Income Certificate',
      'Age Proof',
      'Bank Account Details',
      'Aadhaar Card',
      'Recent Photographs',
      'Ration Card'
    ],
  },
  {
    id: 'REV-503',
    slug: 'girl-child-protection',
    name: 'Girl Child Protection Scheme',
    description: 'Government scheme providing financial assistance for girl child education and welfare.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 100,
    professionalFee: 650,
    gst: 117,
    totalPayable: 867,
    price: 867,
    fee: '650',
    governmentFee: '₹100',
    processingTime: '30-60 days',
    requiredDocuments: [
      'Birth Certificate of Girl Child',
      'Income Certificate',
      'Ration Card',
      'Bank Account Details (in mother\'s name)',
      'School Certificate',
      'Aadhaar Card of Parents',
      'Photographs of Child and Parents'
    ],
  },

  // ========================================
  // IDENTITY & CARDS
  // ========================================
  {
    id: 'IDC-001',
    slug: 'aadhaar',
    name: 'Aadhaar Card',
    description: 'Apply for new Aadhaar card, update details, or get corrections done.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 0,
    professionalFee: 299,
    gst: 53.82,
    totalPayable: 352.82,
    price: 352.82,
    fee: '299',
    governmentFee: 'Free',
    processingTime: '15-30 days',
    requiredDocuments: [
      'Proof of Identity',
      'Proof of Address',
      'Date of Birth Proof',
      'Photograph'
    ],
    popular: true,
  },
  {
    id: 'IDC-002',
    slug: 'pan-card',
    name: 'PAN Card',
    description: 'Apply for new PAN card or request duplicate/correction.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 110,
    professionalFee: 399,
    gst: 71.82,
    totalPayable: 580.82,
    price: 580.82,
    fee: '399',
    governmentFee: '₹110',
    processingTime: '15-20 days',
    requiredDocuments: [
      'Identity Proof',
      'Address Proof',
      'Date of Birth Proof',
      'Photograph'
    ],
    popular: true,
  },
  {
    id: 'IDC-003',
    slug: 'passport',
    name: 'Passport',
    description: 'Complete assistance for new passport, renewal, or re-issue.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 1500,
    professionalFee: 799,
    gst: 143.82,
    totalPayable: 2442.82,
    price: 2442.82,
    fee: '799',
    governmentFee: '₹1,500 - ₹2,000',
    processingTime: '30-45 days',
    requiredDocuments: [
      'Birth Certificate',
      'Address Proof',
      'Identity Proof',
      'Passport Photos'
    ],
    popular: true,
  },
  // =============================================================================
// CORRECTED 73 ADDITIONAL SERVICES - NO DUPLICATE IDs
// =============================================================================
// Add these AFTER your existing 18 services
// All IDs are now unique and don't conflict
// =============================================================================

// =============================================================================
// CATEGORY 1: IDENTITY & PERSONAL DOCUMENTS (4 services)
// =============================================================================

{
  id: 'IDC-101',  // Changed from IDC-002 to avoid conflict
  slug: 'voter-id-card',
  name: 'Voter ID Card (Election Card)',
  description: 'Professional assistance for new voter ID enrollment, corrections, and address updates with complete form filling and document verification.',
  category: 'identity',
  categoryGroup: 'Identity & Certificates',
  statutoryFee: 0,
  professionalFee: 499,
  gst: 90,
  totalPayable: 589,
  price: 589,
  fee: '₹589',
  governmentFee: 'Free',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Aadhaar Card',
    'Address Proof (Electricity Bill / Ration Card / Rent Agreement)',
    'Date of Birth Proof (Birth Certificate / School Certificate)',
    'Passport Size Photo (Recent)',
    'Form 6 (New Registration) / Form 8 (Correction)',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'IDC-102',  // Changed from IDC-003 to avoid conflict
  slug: 'driving-license',
  name: 'Driving License (DL)',
  description: 'Complete support for learner license, permanent license, renewal, and duplicate DL with appointment booking and RTO coordination.',
  category: 'identity',
  categoryGroup: 'Identity & Certificates',
  statutoryFee: 200,
  professionalFee: 1299,
  gst: 234,
  totalPayable: 1733,
  price: 1733,
  fee: '₹1,733',
  governmentFee: '₹200',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Aadhaar Card',
    'Address Proof (Current)',
    'Age Proof (Birth Certificate / School Certificate)',
    'Passport Size Photos (4 copies)',
    'Medical Certificate (For Transport Vehicle)',
    'Learner License (For Permanent DL)',
    'Form 2 / Form 4 / Form 9 (As applicable)',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'IDC-103',  // Changed from IDC-004 to avoid conflict
  slug: 'ration-card',
  name: 'Ration Card (Smart Card)',
  description: 'Hassle-free ration card application for new cards, family member additions, deletions, and address changes with complete documentation.',
  category: 'identity',
  categoryGroup: 'Identity & Certificates',
  statutoryFee: 0,
  professionalFee: 799,
  gst: 144,
  totalPayable: 943,
  price: 943,
  fee: '₹943',
  governmentFee: 'Free',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Aadhaar Card (All Family Members)',
    'Family Income Proof',
    'Address Proof (Ownership / Rent Agreement)',
    'Electricity Bill / Water Bill',
    'Family Photo (All members together)',
    'Bank Passbook (First page)',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'PCD-101',  // Changed from PCD-001 to avoid any conflicts
  slug: 'marriage-certificate',
  name: 'Marriage Certificate (Registration)',
  description: 'Professional marriage registration services including certificate issuance, late registration support, and legal documentation assistance.',
  category: 'certificates',
  categoryGroup: 'Identity & Certificates',
  statutoryFee: 100,
  professionalFee: 1499,
  gst: 270,
  totalPayable: 1869,
  price: 1869,
  fee: '₹1,869',
  governmentFee: '₹100',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Marriage Invitation Card',
    'Marriage Photos (Wedding ceremony)',
    'Aadhaar Card (Both Bride and Groom)',
    'Address Proof (Both parties)',
    'Age Proof (Birth Certificate / School Certificate)',
    'Affidavit (Joint declaration of marriage)',
    'Witness Details (2 witnesses with ID proof)',
    'Priest Certificate (If religious ceremony)',
  ],
  popular: false,
  comingSoon: false,
},

// =============================================================================
// CATEGORY 2: EDUCATION & SPECIAL CERTIFICATES (5 services)
// =============================================================================

{
  id: 'EDU-001',
  slug: 'inter-caste-marriage-certificate',
  name: 'Inter-Caste Marriage Certificate',
  description: 'Expert guidance for inter-caste marriage certificate with complete statutory benefits processing and incentive scheme application support.',
  category: 'certificates',
  categoryGroup: 'Identity & Certificates',
  statutoryFee: 0,
  professionalFee: 1999,
  gst: 360,
  totalPayable: 2359,
  price: 2359,
  fee: '₹2,359',
  governmentFee: 'Free',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Marriage Certificate (Registered)',
    'Community Certificate (Both Bride and Groom)',
    'Aadhaar Card (Both parties)',
    'Wedding Photos',
    'Affidavit (Joint declaration)',
    'Income Certificate (Both families)',
    'Bank Account Details (Joint account preferred)',
    'Witness Statements (2 witnesses)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'EDU-002',
  slug: 'ncc-certificate',
  name: 'NCC Certificate (National Cadet Corps)',
  description: 'Professional assistance for NCC A, B, and C certificate verification and attestation for educational and employment purposes.',
  category: 'certificates',
  categoryGroup: 'Identity & Certificates',
  statutoryFee: 0,
  professionalFee: 699,
  gst: 126,
  totalPayable: 825,
  price: 825,
  fee: '₹825',
  governmentFee: 'Free',
  processingTime: '15-30 days',
  requiredDocuments: [
    'NCC Certificate (Original)',
    'School / College ID Card',
    'Aadhaar Card',
    'Passport Size Photo',
    'Verification Letter from NCC Unit',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'EDU-003',
  slug: 'sports-certificate',
  name: 'Sports Certificate (State/National Level)',
  description: 'Complete support for sports achievement certificate verification for educational admissions and government job applications.',
  category: 'certificates',
  categoryGroup: 'Identity & Certificates',
  statutoryFee: 0,
  professionalFee: 799,
  gst: 144,
  totalPayable: 943,
  price: 943,
  fee: '₹943',
  governmentFee: 'Free',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Sports Participation Certificate',
    'Medal / Trophy Photos',
    'School / College Sports Certificate',
    'Aadhaar Card',
    'Passport Size Photo',
    'Event Organizer Letter',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'EDU-004',
  slug: 'differently-abled-certificate',
  name: 'Differently Abled Certificate (Disability Certificate)',
  description: 'Compassionate and professional support for disability certificate with complete medical board coordination and benefits enrollment.',
  category: 'certificates',
  categoryGroup: 'Identity & Certificates',
  statutoryFee: 0,
  professionalFee: 1299,
  gst: 234,
  totalPayable: 1533,
  price: 1533,
  fee: '₹1,533',
  governmentFee: 'Free',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Medical Certificate (From Government Doctor)',
    'Medical Reports (All relevant tests and scans)',
    'Aadhaar Card',
    'Address Proof',
    'Passport Size Photos (3 copies)',
    'Income Certificate',
    'Bank Account Details',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'EDU-005',
  slug: 'ex-serviceman-certificate',
  name: 'Ex-Serviceman Certificate (ESM)',
  description: 'Dedicated support for ex-servicemen certificate processing with complete documentation for benefits, pensions, and employment reservations.',
  category: 'certificates',
  categoryGroup: 'Identity & Certificates',
  statutoryFee: 0,
  professionalFee: 999,
  gst: 180,
  totalPayable: 1179,
  price: 1179,
  fee: '₹1,179',
  governmentFee: 'Free',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Discharge Certificate (From Armed Forces)',
    'Service Records',
    'Identity Card (Defence)',
    'Aadhaar Card',
    'Bank Passbook',
    'Passport Size Photos (2 copies)',
  ],
  popular: false,
  comingSoon: false,
},

// =============================================================================
// CATEGORY 3: PROPERTY & LAND SERVICES (11 services)
// =============================================================================

{
  id: 'PRP-001',
  slug: 'encumbrance-certificate',
  name: 'Encumbrance Certificate (EC)',
  description: 'Fast-track property transaction verification with comprehensive EC for any period, essential for property purchases and loans.',
  category: 'property',
  categoryGroup: 'Property & Land',
  statutoryFee: 50,
  professionalFee: 799,
  gst: 144,
  totalPayable: 993,
  price: 993,
  fee: '₹993',
  governmentFee: '₹50',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Property Survey Number',
    'Property Address (Complete)',
    'Owner Details (Name and Address)',
    'Period Required (From-To dates)',
    'Village/Town Name',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'PRP-002',
  slug: 'patta-mutation',
  name: 'Patta Mutation (Name Transfer)',
  description: 'Seamless property ownership transfer in government records with complete mutation processing and updated patta issuance.',
  category: 'property',
  categoryGroup: 'Property & Land',
  statutoryFee: 100,
  professionalFee: 2499,
  gst: 450,
  totalPayable: 3049,
  price: 3049,
  fee: '₹3,049',
  governmentFee: '₹100',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Sale Deed / Gift Deed (Registered)',
    'Previous Patta (Original)',
    'Encumbrance Certificate (Latest)',
    'Property Tax Receipt (Paid up to date)',
    'Aadhaar Card (New owner)',
    'Address Proof',
    'Survey Map (If available)',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'PRP-003',
  slug: 'land-conversion',
  name: 'Land Conversion (Agricultural to Non-Agricultural)',
  description: 'Expert assistance for land use conversion with complete legal compliance, DTCP approval, and land authority coordination.',
  category: 'property',
  categoryGroup: 'Property & Land',
  statutoryFee: 5000,
  professionalFee: 9999,
  gst: 1800,
  totalPayable: 16799,
  price: 16799,
  fee: '₹16,799',
  governmentFee: '₹5,000+',
  processingTime: '60-90 days',
  requiredDocuments: [
    'Original Patta and Chitta',
    'Survey Map',
    'Encumbrance Certificate (30 years)',
    'Land Ownership Proof',
    'Layout Plan (If applicable)',
    'DTCP Approval (If required)',
    'NOC from Panchayat / Municipality',
    'Property Tax Receipts',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'PRP-004',
  slug: 'land-partition',
  name: 'Land Partition (Property Division)',
  description: 'Professional land partition services with family settlement documentation, survey coordination, and individual patta issuance.',
  category: 'property',
  categoryGroup: 'Property & Land',
  statutoryFee: 500,
  professionalFee: 4999,
  gst: 900,
  totalPayable: 6399,
  price: 6399,
  fee: '₹6,399',
  governmentFee: '₹500',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Original Patta (Joint ownership)',
    'Family Settlement Deed (If applicable)',
    'Consent Letter (All co-owners)',
    'Survey Report (New partition)',
    'Aadhaar Card (All parties)',
    'Property Tax Receipt',
    'Encumbrance Certificate',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'PRP-005',
  slug: 'building-plan-approval',
  name: 'Building Plan Approval',
  description: 'Complete architectural plan submission and approval with DTCP/CMDA coordination and construction permit processing.',
  category: 'property',
  categoryGroup: 'Property & Land',
  statutoryFee: 2000,
  professionalFee: 7999,
  gst: 1440,
  totalPayable: 11439,
  price: 11439,
  fee: '₹11,439',
  governmentFee: '₹2,000+',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Property Ownership Documents (Patta/Sale Deed)',
    'Encumbrance Certificate (30 years)',
    'Survey Map (Site plan)',
    'Architectural Drawings (Floor plans, elevations)',
    'Structural Design (Engineer certified)',
    'Soil Test Report',
    'Setback Compliance Documents',
    'Property Tax Paid Receipt',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'PRP-006',
  slug: 'occupancy-certificate',
  name: 'Occupancy Certificate (OC)',
  description: 'Essential post-construction OC with inspection coordination and final completion certificate from municipal authorities.',
  category: 'property',
  categoryGroup: 'Property & Land',
  statutoryFee: 1000,
  professionalFee: 5999,
  gst: 1080,
  totalPayable: 8079,
  price: 8079,
  fee: '₹8,079',
  governmentFee: '₹1,000',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Approved Building Plan',
    'Completion Certificate (From Engineer/Architect)',
    'Property Tax Receipt (Updated)',
    'Photographs (Construction as per plan)',
    'Water Connection Proof',
    'Electricity Connection Proof',
    'Fire Safety Certificate (If applicable)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'PRP-007',
  slug: 'completion-certificate',
  name: 'Completion Certificate',
  description: 'Professional completion certificate processing with final inspection coordination and compliance verification for residential/commercial projects.',
  category: 'property',
  categoryGroup: 'Property & Land',
  statutoryFee: 500,
  professionalFee: 3999,
  gst: 720,
  totalPayable: 5219,
  price: 5219,
  fee: '₹5,219',
  governmentFee: '₹500',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Approved Building Plan',
    'Inspection Report',
    'Engineer/Architect Certificate',
    'Construction Photos',
    'Property Tax Receipt',
    'Utility Connection Certificates',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'PRP-008',
  slug: 'property-tax-assessment',
  name: 'Property Tax Assessment',
  description: 'Complete property tax assessment services with valuation report, tax calculation, and payment processing for all property types.',
  category: 'property',
  categoryGroup: 'Property & Land',
  statutoryFee: 0,
  professionalFee: 1499,
  gst: 270,
  totalPayable: 1769,
  price: 1769,
  fee: '₹1,769',
  governmentFee: 'Varies',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Property Ownership Proof',
    'Building Details (Area, floors, usage)',
    'Encumbrance Certificate',
    'Previous Tax Receipts (If available)',
    'Property Photos',
    'Address Proof',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'PRP-009',
  slug: 'survey-resurvey',
  name: 'Survey / Resurvey Application',
  description: 'Professional survey application with revenue department coordination for accurate land measurement and boundary demarcation.',
  category: 'property',
  categoryGroup: 'Property & Land',
  statutoryFee: 500,
  professionalFee: 2999,
  gst: 540,
  totalPayable: 4039,
  price: 4039,
  fee: '₹4,039',
  governmentFee: '₹500',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Patta and Chitta',
    'Previous Survey Documents',
    'Adjacent Property Details',
    'Ownership Proof',
    'Reason for Resurvey (Written statement)',
    'Property Tax Receipt',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'PRP-010',
  slug: 'patta-name-correction',
  name: 'Patta Name Correction',
  description: 'Quick name correction in property records for spelling errors, name changes after marriage, or legal name updates.',
  category: 'property',
  categoryGroup: 'Property & Land',
  statutoryFee: 50,
  professionalFee: 1499,
  gst: 270,
  totalPayable: 1819,
  price: 1819,
  fee: '₹1,819',
  governmentFee: '₹50',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Original Patta (With error)',
    'Proof of Correct Name (Aadhaar/Passport/School Certificate)',
    'Affidavit (Name correction)',
    'Gazette Notification (If legal name change)',
    'Property Tax Receipt',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'PRP-011',
  slug: 'land-dispute-resolution',
  name: 'Land Dispute Resolution Support',
  description: 'Expert mediation and documentation support for property boundary disputes, encroachment issues, and ownership conflicts.',
  category: 'property',
  categoryGroup: 'Property & Land',
  statutoryFee: 0,
  professionalFee: 9999,
  gst: 1800,
  totalPayable: 11799,
  price: 11799,
  fee: '₹11,799',
  governmentFee: 'Varies',
  processingTime: '60-90 days',
  requiredDocuments: [
    'All Property Documents (Patta, Sale Deeds, etc.)',
    'Survey Maps (Old and new)',
    'Encumbrance Certificate',
    'Dispute Details (Written statement)',
    'Photographs of Disputed Area',
    'Witness Statements (If available)',
    'Legal Notices (If issued)',
  ],
  popular: false,
  comingSoon: false,
},

// =============================================================================
// CATEGORY 4: BUSINESS & LICENSING (15 services)
// =============================================================================

{
  id: 'BUS-002',
  slug: 'food-license-fssai',
  name: 'Food License (FSSAI)',
  description: 'Complete FSSAI registration for food businesses including restaurants, cloud kitchens, and food manufacturing with state and central licenses.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 100,
  professionalFee: 2999,
  gst: 540,
  totalPayable: 3639,
  price: 3639,
  fee: '₹3,639',
  governmentFee: '₹100',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Business PAN Card',
    'Shop/Establishment Proof (Rent Agreement/Ownership)',
    'Aadhaar Card (Owner)',
    'Bank Account Details',
    'Food Safety Plan',
    'List of Food Products (If manufacturing)',
    'Water Test Report (If required)',
    'Medical Certificate (Food handler)',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'BUS-003',
  slug: 'shops-establishments-license',
  name: 'Shops & Establishments License',
  description: 'Mandatory registration for all commercial establishments with complete labor law compliance and certificate issuance.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 200,
  professionalFee: 1999,
  gst: 360,
  totalPayable: 2559,
  price: 2559,
  fee: '₹2,559',
  governmentFee: '₹200',
  processingTime: '15-30 days',
  requiredDocuments: [
    'PAN Card (Business)',
    'Address Proof (Shop/Office)',
    'Aadhaar Card (Owner)',
    'Rent Agreement / Ownership Proof',
    'Employee Details (If applicable)',
    'Partnership Deed (If partnership)',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'BUS-004',
  slug: 'factory-license',
  name: 'Factory License',
  description: 'Complete factory registration under Factories Act with labor department coordination and compliance documentation.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 1000,
  professionalFee: 7999,
  gst: 1440,
  totalPayable: 10439,
  price: 10439,
  fee: '₹10,439',
  governmentFee: '₹1,000',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Factory Plan (Site layout)',
    'Machinery Details',
    'Manufacturing Process Flow',
    'Pollution Control NOC',
    'Fire Safety Certificate',
    'Building Plan Approval',
    'Power Connection Details',
    'Employee Strength Details',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'BUS-005',
  slug: 'msme-udyam-registration',
  name: 'MSME / Udyam Registration',
  description: 'Fast and easy Udyam registration with government benefits access, priority lending, and tax exemptions for small businesses.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 0,
  professionalFee: 1999,
  gst: 360,
  totalPayable: 2359,
  price: 2359,
  fee: '₹2,359',
  governmentFee: 'Free',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Aadhaar Card (Promoter)',
    'PAN Card (Business)',
    'Business Address Proof',
    'Bank Account Details',
    'Investment Details (Plant & machinery)',
    'Turnover Details (Previous year)',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'BUS-006',
  slug: 'gst-registration',
  name: 'GST Registration',
  description: 'Comprehensive GST registration services with HSN code selection, GSTIN activation, and return filing setup for all business types.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 0,
  professionalFee: 2999,
  gst: 540,
  totalPayable: 3539,
  price: 3539,
  fee: '₹3,539',
  governmentFee: 'Free',
  processingTime: '15-30 days',
  requiredDocuments: [
    'PAN Card (Business/Proprietor)',
    'Aadhaar Card (Owner)',
    'Business Address Proof (Rent/Ownership)',
    'Bank Account Details (Cancelled cheque)',
    'Digital Signature (If company)',
    'Business Constitution Proof (Partnership deed/MOA)',
    'Photographs (Owner)',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'BUS-007',
  slug: 'professional-tax-registration',
  name: 'Professional Tax Registration',
  description: 'Complete professional tax enrollment for businesses and professionals with monthly payment setup and compliance management.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 0,
  professionalFee: 1499,
  gst: 270,
  totalPayable: 1769,
  price: 1769,
  fee: '₹1,769',
  governmentFee: 'Varies',
  processingTime: '15-30 days',
  requiredDocuments: [
    'PAN Card (Business)',
    'Business Registration Proof',
    'Aadhaar Card (Owner)',
    'Employee List (If applicable)',
    'Bank Account Details',
    'Address Proof',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'BUS-008',
  slug: 'import-export-code',
  name: 'Import Export Code (IEC)',
  description: 'Essential IEC registration for international trade with customs clearance support and DGFT coordination.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 500,
  professionalFee: 2999,
  gst: 540,
  totalPayable: 4039,
  price: 4039,
  fee: '₹4,039',
  governmentFee: '₹500',
  processingTime: '15-30 days',
  requiredDocuments: [
    'PAN Card (Business)',
    'Aadhaar Card (Authorized signatory)',
    'Bank Certificate (Current account)',
    'Business Address Proof',
    'Cancelled Cheque',
    'Digital Signature (If company)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'BUS-009',
  slug: 'pawn-broker-license',
  name: 'Pawn Broker License',
  description: 'Specialized pawn broker license processing with police verification, security compliance, and complete legal documentation.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 500,
  professionalFee: 4999,
  gst: 900,
  totalPayable: 6399,
  price: 6399,
  fee: '₹6,399',
  governmentFee: '₹500',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Business Plan',
    'Shop Ownership/Rent Proof',
    'Police Verification Certificate',
    'Character Certificate',
    'Bank Solvency Certificate',
    'Aadhaar & PAN (Owner)',
    'Passport Size Photos',
    'Security Arrangements Details',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'BUS-010',
  slug: 'liquor-license',
  name: 'Liquor License',
  description: 'Complete liquor license application for bars, restaurants, and retail with TASMAC coordination and compliance management.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 10000,
  professionalFee: 19999,
  gst: 3600,
  totalPayable: 33599,
  price: 33599,
  fee: '₹33,599',
  governmentFee: '₹10,000+',
  processingTime: '60-90 days',
  requiredDocuments: [
    'Building Plan Approval',
    'Fire NOC',
    'Health Department NOC',
    'Police NOC',
    'Business Plan',
    'Character Certificate (Owner)',
    'Financial Statements',
    'Bank Solvency Certificate',
    'Property Documents',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'BUS-011',
  slug: 'explosive-license',
  name: 'Explosive License',
  description: 'High-security explosive license with complete safety compliance, PESO coordination, and storage facility verification.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 5000,
  professionalFee: 14999,
  gst: 2700,
  totalPayable: 22699,
  price: 22699,
  fee: '₹22,699',
  governmentFee: '₹5,000+',
  processingTime: '60-90 days',
  requiredDocuments: [
    'Detailed Business Plan',
    'Storage Facility Plans (Technical)',
    'Safety Equipment Details',
    'Fire Safety Certificate',
    'Police Verification',
    'Character Certificate',
    'Technical Qualification Certificates',
    'Insurance Coverage Proof',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'BUS-012',
  slug: 'arms-license',
  name: 'Arms License',
  description: 'Professional arms license application with police verification, training certification, and complete legal compliance support.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 3000,
  professionalFee: 9999,
  gst: 1800,
  totalPayable: 14799,
  price: 14799,
  fee: '₹14,799',
  governmentFee: '₹3,000',
  processingTime: '60-90 days',
  requiredDocuments: [
    'Application Form (Detailed)',
    'Character Certificate (Police)',
    'Medical Fitness Certificate',
    'Reason for License (Affidavit)',
    'Property Ownership Proof',
    'Income Tax Returns (3 years)',
    'Photographs',
    'Witness Details',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'BUS-013',
  slug: 'hotel-license',
  name: 'Hotel License',
  description: 'Complete hotel registration with tourism department, fire safety, health compliance, and all statutory clearances.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 2000,
  professionalFee: 7999,
  gst: 1440,
  totalPayable: 11439,
  price: 11439,
  fee: '₹11,439',
  governmentFee: '₹2,000',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Building Plan Approval',
    'Fire NOC',
    'Health Department NOC',
    'Pollution Control NOC',
    'Trade License',
    'FSSAI License (If food service)',
    'Police Verification',
    'Property Documents',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'BUS-014',
  slug: 'restaurant-license',
  name: 'Restaurant License',
  description: 'All-in-one restaurant licensing with FSSAI, trade license, health permits, and complete operational clearances.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 500,
  professionalFee: 4999,
  gst: 900,
  totalPayable: 6399,
  price: 6399,
  fee: '₹6,399',
  governmentFee: '₹500',
  processingTime: '30-45 days',
  requiredDocuments: [
    'FSSAI License',
    'Trade License',
    'Fire Safety Certificate',
    'Health Department NOC',
    'Building Ownership/Rent Proof',
    'Kitchen Layout Plan',
    'Waste Management Plan',
    'Water Quality Certificate',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'BUS-015',
  slug: 'medical-shop-license',
  name: 'Medical Shop License (Drug License)',
  description: 'Complete drug retail license with pharmacist registration, drug control department coordination, and compliance setup.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 1000,
  professionalFee: 5999,
  gst: 1080,
  totalPayable: 8079,
  price: 8079,
  fee: '₹8,079',
  governmentFee: '₹1,000',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Pharmacy Degree Certificate (Pharmacist)',
    'Registration Certificate (Pharmacy Council)',
    'Shop Ownership/Rent Agreement',
    'Shop Layout Plan',
    'Storage Facility Details',
    'PAN Card (Business)',
    'Aadhaar Card (Owner & Pharmacist)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'BUS-016',
  slug: 'petrol-bunk-license',
  name: 'Petrol Bunk License',
  description: 'Comprehensive fuel retail authorization with petroleum ministry, fire safety, environmental clearances, and NOC processing.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 50000,
  professionalFee: 49999,
  gst: 9000,
  totalPayable: 108999,
  price: 108999,
  fee: '₹1,08,999',
  governmentFee: '₹50,000+',
  processingTime: '60-90 days',
  requiredDocuments: [
    'Land Ownership Proof (Minimum area requirement)',
    'Site Plan and Layout',
    'Fire Safety Certificate',
    'Environmental Clearance',
    'Pollution Control NOC',
    'Local Authority NOC',
    'Financial Capability Certificate',
    'Business Plan (Detailed)',
    'Bank Guarantee',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'BUS-017',
  slug: 'small-scale-industry-registration',
  name: 'Small Scale Industry (SSI) Registration',
  description: 'SSI registration with state benefits, subsidies, and industrial area allocation support for manufacturing units.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 0,
  professionalFee: 2999,
  gst: 540,
  totalPayable: 3539,
  price: 3539,
  fee: '₹3,539',
  governmentFee: 'Free',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Business Plan',
    'Machinery Details',
    'Investment Proof',
    'Factory Location Proof',
    'PAN Card (Business)',
    'Aadhaar Card (Promoter)',
    'Bank Account Details',
    'Product Details',
  ],
  popular: false,
  comingSoon: false,
},

// =============================================================================
// CATEGORY 5: VEHICLE & TRANSPORT (9 services)
// =============================================================================

{
  id: 'VEH-001',
  slug: 'vehicle-registration',
  name: 'Vehicle Registration (New)',
  description: 'Complete new vehicle registration with RTO coordination, number plate allocation, and RC book issuance for all vehicle types.',
  category: 'vehicle',
  categoryGroup: 'Vehicle & Transport',
  statutoryFee: 500,
  professionalFee: 1999,
  gst: 360,
  totalPayable: 2859,
  price: 2859,
  fee: '₹2,859',
  governmentFee: '₹500+',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Invoice (Vehicle purchase)',
    'Insurance Certificate (Valid)',
    'Aadhaar Card',
    'Address Proof',
    'Form 20 (Application)',
    'Form 21 (Sale certificate)',
    'PUC Certificate',
    'Hypothecation Letter (If loan)',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'VEH-002',
  slug: 'vehicle-transfer',
  name: 'Vehicle Transfer (RC Transfer)',
  description: 'Smooth ownership transfer with buyer-seller coordination, NOC processing, and updated RC book in new owner name.',
  category: 'vehicle',
  categoryGroup: 'Vehicle & Transport',
  statutoryFee: 300,
  professionalFee: 1499,
  gst: 270,
  totalPayable: 2069,
  price: 2069,
  fee: '₹2,069',
  governmentFee: '₹300',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Original RC Book',
    'Insurance Certificate (Transferred)',
    'Form 29 (NOC)',
    'Form 30 (Transfer)',
    'Sale Agreement',
    'Aadhaar Card (Buyer and Seller)',
    'Address Proof (Buyer)',
    'PUC Certificate',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'VEH-003',
  slug: 'vehicle-hypothecation',
  name: 'Vehicle Hypothecation (Add/Remove)',
  description: 'Fast hypothecation addition for vehicle loans and termination after loan closure with updated RC book.',
  category: 'vehicle',
  categoryGroup: 'Vehicle & Transport',
  statutoryFee: 100,
  professionalFee: 999,
  gst: 180,
  totalPayable: 1279,
  price: 1279,
  fee: '₹1,279',
  governmentFee: '₹100',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Original RC Book',
    'NOC from Bank/Finance Company (For removal)',
    'Loan Sanction Letter (For addition)',
    'Aadhaar Card',
    'Form 35 (Hypothecation)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'VEH-004',
  slug: 'duplicate-rc',
  name: 'Duplicate RC Book',
  description: 'Quick duplicate RC issuance for lost or damaged registration certificates with police verification support.',
  category: 'vehicle',
  categoryGroup: 'Vehicle & Transport',
  statutoryFee: 100,
  professionalFee: 799,
  gst: 144,
  totalPayable: 1043,
  price: 1043,
  fee: '₹1,043',
  governmentFee: '₹100',
  processingTime: '15-30 days',
  requiredDocuments: [
    'FIR Copy (If lost)',
    'Affidavit (Lost/Damaged)',
    'Insurance Certificate',
    'Aadhaar Card',
    'Address Proof',
    'Form 26 (Duplicate RC)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'VEH-005',
  slug: 'noc-vehicle-relocation',
  name: 'NOC for Vehicle Relocation (State Transfer)',
  description: 'Interstate vehicle transfer with NOC from original RTO and re-registration in new state with complete documentation.',
  category: 'vehicle',
  categoryGroup: 'Vehicle & Transport',
  statutoryFee: 500,
  professionalFee: 2499,
  gst: 450,
  totalPayable: 3449,
  price: 3449,
  fee: '₹3,449',
  governmentFee: '₹500',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Original RC Book',
    'Insurance Certificate',
    'Tax Clearance Certificate',
    'Address Proof (New state)',
    'Aadhaar Card',
    'Form 27 (NOC application)',
    'Form 28 (Re-registration)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'VEH-006',
  slug: 'fitness-certificate',
  name: 'Fitness Certificate (Commercial Vehicle)',
  description: 'Mandatory fitness testing and certification for commercial vehicles with inspection coordination and renewal support.',
  category: 'vehicle',
  categoryGroup: 'Vehicle & Transport',
  statutoryFee: 200,
  professionalFee: 1299,
  gst: 234,
  totalPayable: 1733,
  price: 1733,
  fee: '₹1,733',
  governmentFee: '₹200',
  processingTime: '15-30 days',
  requiredDocuments: [
    'RC Book',
    'Insurance Certificate (Valid)',
    'Tax Receipt (Paid)',
    'Pollution Certificate (PUC)',
    'Vehicle for Inspection',
    'Form 22 (Fitness application)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'VEH-007',
  slug: 'learners-license',
  name: 'Learner License (LL)',
  description: 'Complete learner license application with test booking, RTO coordination, and first-time applicant guidance.',
  category: 'vehicle',
  categoryGroup: 'Vehicle & Transport',
  statutoryFee: 150,
  professionalFee: 699,
  gst: 126,
  totalPayable: 975,
  price: 975,
  fee: '₹975',
  governmentFee: '₹150',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Age Proof (Birth Certificate/School Certificate)',
    'Address Proof',
    'Aadhaar Card',
    'Passport Size Photos (4 copies)',
    'Form 2 (Learner application)',
    'Medical Certificate (For Transport)',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'VEH-008',
  slug: 'permanent-license',
  name: 'Permanent Driving License',
  description: 'Upgrade from learner to permanent license with driving test coordination and full DL issuance.',
  category: 'vehicle',
  categoryGroup: 'Vehicle & Transport',
  statutoryFee: 200,
  professionalFee: 1299,
  gst: 234,
  totalPayable: 1733,
  price: 1733,
  fee: '₹1,733',
  governmentFee: '₹200',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Learner License (Valid)',
    'Aadhaar Card',
    'Address Proof',
    'Passport Size Photos (4 copies)',
    'Form 4 (Permanent DL)',
    'Medical Certificate (For Transport)',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'VEH-009',
  slug: 'international-driving-permit',
  name: 'International Driving Permit (IDP)',
  description: 'International driving permit for overseas travel with quick processing and global acceptance documentation.',
  category: 'vehicle',
  categoryGroup: 'Vehicle & Transport',
  statutoryFee: 1000,
  professionalFee: 1999,
  gst: 360,
  totalPayable: 3359,
  price: 3359,
  fee: '₹3,359',
  governmentFee: '₹1,000',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Valid Indian Driving License',
    'Passport (Valid)',
    'Visa Copy (If available)',
    'Aadhaar Card',
    'Passport Size Photos (2 copies)',
    'Form 4A (IDP application)',
  ],
  popular: false,
  comingSoon: false,
},

// =============================================================================
// CATEGORY 6: LEGAL & COURT SERVICES (7 services)
// =============================================================================

{
  id: 'LEG-001',
  slug: 'affidavit-drafting',
  name: 'Affidavit Drafting & Notarization',
  description: 'Professional legal affidavit drafting for all purposes with notary coordination and stamp paper arrangement.',
  category: 'legal',
  categoryGroup: 'Legal & Court',
  statutoryFee: 100,
  professionalFee: 799,
  gst: 144,
  totalPayable: 1043,
  price: 1043,
  fee: '₹1,043',
  governmentFee: '₹100',
  processingTime: '1-2 days',
  requiredDocuments: [
    'Aadhaar Card',
    'Purpose Details (Written)',
    'Supporting Documents (If any)',
    'Passport Size Photo',
  ],
  popular: true,
  comingSoon: false,
},

{
  id: 'LEG-002',
  slug: 'notary-services',
  name: 'Notary Services',
  description: 'Complete notarization services for documents with registered notary coordination and legal attestation.',
  category: 'legal',
  categoryGroup: 'Legal & Court',
  statutoryFee: 50,
  professionalFee: 499,
  gst: 90,
  totalPayable: 639,
  price: 639,
  fee: '₹639',
  governmentFee: '₹50',
  processingTime: '1-2 days',
  requiredDocuments: [
    'Original Documents (To be notarized)',
    'Aadhaar Card',
    'Passport Size Photo',
    'Witness Details (If required)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'LEG-003',
  slug: 'power-of-attorney',
  name: 'Power of Attorney (POA)',
  description: 'Complete POA preparation and registration for general or specific purposes with legal validity and notarization.',
  category: 'legal',
  categoryGroup: 'Legal & Court',
  statutoryFee: 1000,
  professionalFee: 2999,
  gst: 540,
  totalPayable: 4539,
  price: 4539,
  fee: '₹4,539',
  governmentFee: '₹1,000',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Aadhaar Card (Both Principal and Agent)',
    'Address Proof (Both parties)',
    'Passport Size Photos (Both)',
    'Purpose Description (Written)',
    'Property Documents (If property-related)',
    'Witness Details (2 witnesses)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'LEG-004',
  slug: 'will-drafting',
  name: 'Will Drafting & Registration',
  description: 'Professional will preparation with legal advisor consultation, asset documentation, and optional registration support.',
  category: 'legal',
  categoryGroup: 'Legal & Court',
  statutoryFee: 500,
  professionalFee: 4999,
  gst: 900,
  totalPayable: 6399,
  price: 6399,
  fee: '₹6,399',
  governmentFee: '₹500',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Aadhaar Card (Testator)',
    'Property Documents (All assets)',
    'Beneficiary Details (Complete)',
    'Witness Details (2 witnesses)',
    'Passport Size Photos',
    'Medical Fitness Certificate (If elderly)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'LEG-005',
  slug: 'succession-certificate',
  name: 'Succession Certificate',
  description: 'Complete succession certificate processing for asset inheritance with court filing, hearings, and certificate issuance.',
  category: 'legal',
  categoryGroup: 'Legal & Court',
  statutoryFee: 5000,
  professionalFee: 19999,
  gst: 3600,
  totalPayable: 28599,
  price: 28599,
  fee: '₹28,599',
  governmentFee: '₹5,000+',
  processingTime: '60-90 days',
  requiredDocuments: [
    'Death Certificate (Deceased)',
    'Legal Heir Certificate',
    'Property/Asset Details (All)',
    'Family Tree (Detailed)',
    'Aadhaar Cards (All legal heirs)',
    'Address Proof (All applicants)',
    'Bank Statements/Property Documents',
    'Witness Affidavits',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'LEG-006',
  slug: 'name-change-gazette',
  name: 'Name Change in Gazette',
  description: 'Official name change with government gazette notification and newspaper publication for legal validity across all documents.',
  category: 'legal',
  categoryGroup: 'Legal & Court',
  statutoryFee: 500,
  professionalFee: 2999,
  gst: 540,
  totalPayable: 4039,
  price: 4039,
  fee: '₹4,039',
  governmentFee: '₹500',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Aadhaar Card (Current name)',
    'Affidavit (Name change)',
    'Reason for Change (Detailed)',
    'Newspaper Advertisement (2 papers)',
    'Passport Size Photos (New name)',
    'Address Proof',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'LEG-007',
  slug: 'legal-notice',
  name: 'Legal Notice Drafting & Dispatch',
  description: 'Professional legal notice preparation by advocates for civil, criminal, or property disputes with registered post.',
  category: 'legal',
  categoryGroup: 'Legal & Court',
  statutoryFee: 0,
  professionalFee: 2999,
  gst: 540,
  totalPayable: 3539,
  price: 3539,
  fee: '₹3,539',
  governmentFee: 'Varies',
  processingTime: '3-7 days',
  requiredDocuments: [
    'Case Details (Written)',
    'Supporting Documents',
    'Recipient Details (Full address)',
    'Your Aadhaar Card',
    'Previous Correspondence (If any)',
  ],
  popular: false,
  comingSoon: false,
},

// =============================================================================
// CATEGORY 7: WELFARE & PENSION SCHEMES (15 services)
// =============================================================================

{
  id: 'WEL-003',
  slug: 'differently-abled-pension',
  name: 'Differently Abled Pension',
  description: 'Monthly pension support for persons with disabilities with complete application processing and benefits enrollment.',
  category: 'welfare',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 799,
  gst: 144,
  totalPayable: 943,
  price: 943,
  fee: '₹943',
  governmentFee: 'Free',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Differently Abled Certificate (40%+ disability)',
    'Aadhaar Card',
    'Income Certificate',
    'Bank Passbook (With photo)',
    'Address Proof',
    'Passport Size Photos (2)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-004',
  slug: 'deserted-wife-pension',
  name: 'Deserted Wife Pension',
  description: 'Financial support for abandoned women with compassionate application processing and monthly pension benefits.',
  category: 'welfare',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 799,
  gst: 144,
  totalPayable: 943,
  price: 943,
  fee: '₹943',
  governmentFee: 'Free',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Aadhaar Card',
    'Marriage Certificate',
    'Income Certificate',
    'Proof of Desertion (Police complaint/Court order)',
    'Bank Passbook',
    'Address Proof',
    'Passport Size Photos (2)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-005',
  slug: 'unmarried-women-pension',
  name: 'Unmarried Women Pension (40+ Age)',
  description: 'Monthly financial assistance for unmarried women above 40 years with complete application and verification support.',
  category: 'welfare',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 799,
  gst: 144,
  totalPayable: 943,
  price: 943,
  fee: '₹943',
  governmentFee: 'Free',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Aadhaar Card',
    'Age Proof (Birth Certificate/School Certificate)',
    'Unmarried Certificate',
    'Income Certificate',
    'Bank Passbook',
    'Address Proof',
    'Passport Size Photos (2)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-006',
  slug: 'agricultural-labourer-pension',
  name: 'Agricultural Labourer Pension',
  description: 'Social security pension for agricultural workers with complete eligibility verification and benefits processing.',
  category: 'welfare',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 799,
  gst: 144,
  totalPayable: 943,
  price: 943,
  fee: '₹943',
  governmentFee: 'Free',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Aadhaar Card',
    'Age Proof (60+ years)',
    'Agricultural Labourer Certificate',
    'Income Certificate',
    'Bank Passbook',
    'Address Proof',
    'Passport Size Photos (2)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-007',
  slug: 'destitute-pension',
  name: 'Destitute Pension',
  description: 'Essential financial support for destitute persons with empathetic application processing and quick benefit disbursement.',
  category: 'welfare',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 799,
  gst: 144,
  totalPayable: 943,
  price: 943,
  fee: '₹943',
  governmentFee: 'Free',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Aadhaar Card',
    'Income Certificate (Nil income)',
    'Destitute Certificate (From Tahsildar)',
    'Bank Passbook',
    'Address Proof',
    'Passport Size Photos (2)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-008',
  slug: 'transgender-pension',
  name: 'Transgender Pension',
  description: 'Inclusive monthly pension support for transgender community with respectful processing and complete benefits access.',
  category: 'welfare',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 799,
  gst: 144,
  totalPayable: 943,
  price: 943,
  fee: '₹943',
  governmentFee: 'Free',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Aadhaar Card (Transgender identity)',
    'Transgender Certificate',
    'Income Certificate',
    'Bank Passbook',
    'Address Proof',
    'Passport Size Photos (2)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-009',
  slug: 'free-bicycle-scheme',
  name: 'Free Bicycle Scheme (Students)',
  description: 'Government bicycle distribution for school students with complete application processing and benefit coordination.',
  category: 'welfare',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 499,
  gst: 90,
  totalPayable: 589,
  price: 589,
  fee: '₹589',
  governmentFee: 'Free',
  processingTime: '30-45 days',
  requiredDocuments: [
    'School ID Card',
    'Aadhaar Card (Student)',
    'Income Certificate (Family)',
    'Community Certificate',
    'School Bonafide Certificate',
    'Passport Size Photo',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-010',
  slug: 'free-laptop-scheme',
  name: 'Free Laptop Scheme (Students)',
  description: 'Government laptop distribution for higher secondary students with application support and eligibility verification.',
  category: 'welfare',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 699,
  gst: 126,
  totalPayable: 825,
  price: 825,
  fee: '₹825',
  governmentFee: 'Free',
  processingTime: '30-45 days',
  requiredDocuments: [
    'School/College ID Card',
    'Aadhaar Card (Student)',
    'Income Certificate (Family)',
    'Community Certificate',
    '10th/12th Mark Sheet',
    'Passport Size Photo',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-011',
  slug: 'marriage-assistance-scheme',
  name: 'Marriage Assistance Scheme',
  description: 'Financial assistance for daughters marriage with complete application processing and benefit disbursement support.',
  category: 'welfare',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 999,
  gst: 180,
  totalPayable: 1179,
  price: 1179,
  fee: '₹1,179',
  governmentFee: 'Free',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Aadhaar Card (Father and Daughter)',
    'Income Certificate (Family)',
    'Community Certificate',
    'Marriage Invitation',
    'Bank Account (Father)',
    'Age Proof (Daughter - 18+ years)',
    'Passport Size Photos',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-012',
  slug: 'housing-scheme',
  name: 'Housing Scheme (Free/Subsidized)',
  description: 'Government housing benefit application with complete eligibility check and allotment processing for economically weaker sections.',
  category: 'welfare',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 1999,
  gst: 360,
  totalPayable: 2359,
  price: 2359,
  fee: '₹2,359',
  governmentFee: 'Free',
  processingTime: '60-90 days',
  requiredDocuments: [
    'Aadhaar Card (All family members)',
    'Income Certificate',
    'Ration Card',
    'No Property Certificate',
    'Bank Account Details',
    'Employment Details',
    'Community Certificate',
    'Passport Size Photos (All members)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-013',
  slug: 'sc-st-scholarship',
  name: 'SC/ST Scholarship',
  description: 'Educational scholarship for SC/ST students with complete application support for pre-matric and post-matric benefits.',
  category: 'welfare',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 799,
  gst: 144,
  totalPayable: 943,
  price: 943,
  fee: '₹943',
  governmentFee: 'Free',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Aadhaar Card (Student)',
    'Community Certificate (SC/ST)',
    'Income Certificate (Family)',
    'School/College ID Card',
    'Mark Sheets (Previous year)',
    'Bank Account (Student/Parent)',
    'Passport Size Photo',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-014',
  slug: 'bc-mbc-scholarship',
  name: 'BC/MBC Scholarship',
  description: 'Educational financial support for BC/MBC students with streamlined application and scholarship disbursement coordination.',
  category: 'welfare',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 799,
  gst: 144,
  totalPayable: 943,
  price: 943,
  fee: '₹943',
  governmentFee: 'Free',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Aadhaar Card (Student)',
    'Community Certificate (BC/MBC)',
    'Income Certificate (Family)',
    'School/College ID Card',
    'Mark Sheets (Previous year)',
    'Bank Account (Student/Parent)',
    'Passport Size Photo',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-015',
  slug: 'minority-scholarship',
  name: 'Minority Scholarship',
  description: 'Educational assistance for minority community students with complete application processing and merit-based benefits.',
  category: 'welfare',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 799,
  gst: 144,
  totalPayable: 943,
  price: 943,
  fee: '₹943',
  governmentFee: 'Free',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Aadhaar Card (Student)',
    'Community Certificate (Minority)',
    'Income Certificate (Family)',
    'School/College ID Card',
    'Mark Sheets (Previous year)',
    'Bank Account (Student/Parent)',
    'Passport Size Photo',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-016',
  slug: 'small-marginal-farmer-certificate',
  name: 'Small/Marginal Farmer Certificate',
  description: 'Official farmer status certificate for agricultural subsidies, loans, and benefit scheme access with land verification.',
  category: 'certificates',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 699,
  gst: 126,
  totalPayable: 825,
  price: 825,
  fee: '₹825',
  governmentFee: 'Free',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Land Ownership Documents (Patta)',
    'Aadhaar Card',
    'Income Certificate',
    'Bank Account Details',
    'Address Proof',
    'Passport Size Photo',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'WEL-017',
  slug: 'bonafide-certificate',
  name: 'Bonafide Certificate',
  description: 'Student bonafide certificate for educational and scholarship purposes with college/school coordination and quick issuance.',
  category: 'certificates',
  categoryGroup: 'Identity & Certificates',
  statutoryFee: 0,
  professionalFee: 299,
  gst: 54,
  totalPayable: 353,
  price: 353,
  fee: '₹353',
  governmentFee: 'Free',
  processingTime: '7-15 days',
  requiredDocuments: [
    'School/College ID Card',
    'Aadhaar Card',
    'Previous Marks Cards',
    'Passport Size Photo',
  ],
  popular: false,
  comingSoon: false,
},

// =============================================================================
// CATEGORY 8: SAFETY & COMPLIANCE (6 services)
// =============================================================================

{
  id: 'SAF-001',
  slug: 'fire-safety-certificate',
  name: 'Fire Safety Certificate',
  description: 'Essential fire safety compliance certificate for commercial buildings with inspection coordination and clearance processing.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 1000,
  professionalFee: 4999,
  gst: 900,
  totalPayable: 6899,
  price: 6899,
  fee: '₹6,899',
  governmentFee: '₹1,000',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Building Plan Approval',
    'Occupancy Certificate',
    'Fire Safety Equipment Details',
    'Emergency Exit Plan',
    'Fire Extinguisher Installation Certificate',
    'Building Ownership/Rent Proof',
    'Business License',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'SAF-002',
  slug: 'pollution-control-noc',
  name: 'Pollution Control NOC',
  description: 'Environmental compliance certificate with pollution board coordination for industries and commercial establishments.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 2000,
  professionalFee: 7999,
  gst: 1440,
  totalPayable: 11439,
  price: 11439,
  fee: '₹11,439',
  governmentFee: '₹2,000',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Factory Plan',
    'Manufacturing Process Details',
    'Effluent Treatment Plan',
    'Air Pollution Control Measures',
    'Waste Disposal Plan',
    'Environmental Impact Assessment',
    'Business Registration Proof',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'SAF-003',
  slug: 'environmental-clearance',
  name: 'Environmental Clearance',
  description: 'Comprehensive environmental impact assessment and clearance for large projects with MoEF coordination.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 10000,
  professionalFee: 29999,
  gst: 5400,
  totalPayable: 45399,
  price: 45399,
  fee: '₹45,399',
  governmentFee: '₹10,000+',
  processingTime: '60-90 days',
  requiredDocuments: [
    'Detailed Project Report',
    'Environmental Impact Assessment Study',
    'Public Consultation Report',
    'Land Documents',
    'Project Plan and Layout',
    'Water Source Details',
    'Waste Management Plan',
    'Green Belt Development Plan',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'SAF-004',
  slug: 'water-noc',
  name: 'Water NOC (PWD/Municipality)',
  description: 'Water connection NOC for construction and commercial use with PWD/municipality coordination and approval processing.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 500,
  professionalFee: 2999,
  gst: 540,
  totalPayable: 4039,
  price: 4039,
  fee: '₹4,039',
  governmentFee: '₹500',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Building Plan Approval',
    'Property Ownership Proof',
    'Water Requirement Details',
    'Existing Connection Details (If any)',
    'Site Plan',
    'Aadhaar Card',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'SAF-005',
  slug: 'electricity-noc',
  name: 'Electricity NOC (TNEB)',
  description: 'Power connection NOC with TANGEDCO coordination for commercial and industrial electrical installations.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 500,
  professionalFee: 2999,
  gst: 540,
  totalPayable: 4039,
  price: 4039,
  fee: '₹4,039',
  governmentFee: '₹500',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Building Plan Approval',
    'Property Ownership Proof',
    'Load Requirement Details',
    'Electrical Installation Certificate',
    'Site Plan',
    'Aadhaar Card',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'SAF-006',
  slug: 'health-noc',
  name: 'Health Department NOC',
  description: 'Health compliance certificate for food, medical, and hospitality establishments with health department coordination.',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 500,
  professionalFee: 3999,
  gst: 720,
  totalPayable: 5219,
  price: 5219,
  fee: '₹5,219',
  governmentFee: '₹500',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Building Plan Approval',
    'FSSAI License (If food related)',
    'Sanitation Plan',
    'Waste Disposal Plan',
    'Water Quality Test Report',
    'Staff Medical Certificates',
    'Business Registration Proof',
  ],
  popular: false,
  comingSoon: false,
},

// =============================================================================
// CATEGORY 9: ADDITIONAL PERSONAL CERTIFICATES (4 services)
// =============================================================================

{
  id: 'PCD-102',  // Changed from PCD-002 to ensure uniqueness
  slug: 'unmarried-certificate',
  name: 'Unmarried Certificate',
  description: 'Official unmarried status certificate for employment, visa, and legal purposes with complete verification support.',
  category: 'certificates',
  categoryGroup: 'Identity & Certificates',
  statutoryFee: 0,
  professionalFee: 699,
  gst: 126,
  totalPayable: 825,
  price: 825,
  fee: '₹825',
  governmentFee: 'Free',
  processingTime: '15-30 days',
  requiredDocuments: [
    'Aadhaar Card',
    'Age Proof (Birth Certificate/School Certificate)',
    'Address Proof',
    'Affidavit (Unmarried status)',
    'Passport Size Photos (2)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'PCD-103',  // Changed from PCD-003 to ensure uniqueness
  slug: 'no-remarriage-certificate',
  name: 'No Remarriage Certificate',
  description: 'Certificate confirming non-remarriage status after divorce or spouse death for legal and benefit purposes.',
  category: 'certificates',
  categoryGroup: 'Identity & Certificates',
  statutoryFee: 0,
  professionalFee: 799,
  gst: 144,
  totalPayable: 943,
  price: 943,
  fee: '₹943',
  governmentFee: 'Free',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Aadhaar Card',
    'Death Certificate (If spouse deceased)',
    'Divorce Decree (If divorced)',
    'Marriage Certificate (Original)',
    'Affidavit (No remarriage)',
    'Address Proof',
    'Passport Size Photos (2)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'PCD-104',  // Changed from PCD-004 to ensure uniqueness
  slug: 'temple-priest-certificate',
  name: 'Temple Priest Certificate (Archaka Certificate)',
  description: 'Official priest eligibility certificate for temple employment with HR&CE department coordination and verification.',
  category: 'certificates',
  categoryGroup: 'Identity & Certificates',
  statutoryFee: 0,
  professionalFee: 1299,
  gst: 234,
  totalPayable: 1533,
  price: 1533,
  fee: '₹1,533',
  governmentFee: 'Free',
  processingTime: '45-60 days',
  requiredDocuments: [
    'Aadhaar Card',
    'Community Certificate',
    'Agama Training Certificate',
    'Traditional Family Background Proof',
    'Age Proof',
    'Address Proof',
    'Passport Size Photos (3)',
  ],
  popular: false,
  comingSoon: false,
},

{
  id: 'PCD-105',  // Changed from PCD-005 to ensure uniqueness
  slug: 'agricultural-labourer-certificate',
  name: 'Agricultural Labourer Certificate',
  description: 'Official status certificate for agricultural workers to access benefits, subsidies, and government schemes.',
  category: 'certificates',
  categoryGroup: 'Welfare & Pensions',
  statutoryFee: 0,
  professionalFee: 699,
  gst: 126,
  totalPayable: 825,
  price: 825,
  fee: '₹825',
  governmentFee: 'Free',
  processingTime: '30-45 days',
  requiredDocuments: [
    'Aadhaar Card',
    'Income Certificate',
    'Employment Details (Affidavit)',
    'Village Officer Certificate',
    'Address Proof',
    'Passport Size Photo',
  ],
  popular: false,
  comingSoon: false,
},

// END OF CORRECTED 73 SERVICES
];

// Helper functions
export function getServiceBySlug(slug: string): Service | undefined {
  return SERVICES.find((service) => service.slug === slug);
}

export function getServicesByCategory(category: string): Service[] {
  return SERVICES.filter((service) => service.category === category);
}

export function getServicesByGroup(group: string): Service[] {
  return SERVICES.filter((service) => service.categoryGroup === group);
}

export function getPopularServices(): Service[] {
  return SERVICES.filter((service) => service.popular === true);
}

export function getAllServices(): Service[] {
  return SERVICES;
}

export function searchServices(query: string): Service[] {
  const lowerQuery = query.toLowerCase();
  return SERVICES.filter(
    (service) =>
      service.name.toLowerCase().includes(lowerQuery) ||
      service.description.toLowerCase().includes(lowerQuery) ||
      service.category.toLowerCase().includes(lowerQuery)
  );
}

// Service category groups
export const serviceGroups = [
  {
    id: 'student-education',
    name: 'Student & Education Solutions',
    description: 'Certificates and documentation for students',
    icon: '🎓',
  },
  {
    id: 'personal-family',
    name: 'Personal & Family Solutions',
    description: 'Family certificates and legal heir documentation',
    icon: '👨‍👩‍👧‍👦',
  },
  {
    id: 'property-asset',
    name: 'Property & Asset Solutions',
    description: 'Land and property documentation services',
    icon: '🏠',
  },
  {
    id: 'business-licensing',
    name: 'Business & Licensing Solutions',
    description: 'Business licenses and NOCs',
    icon: '🏢',
  },
  {
    id: 'social-pension',
    name: 'Social & Pension Schemes',
    description: 'Government welfare and pension schemes',
    icon: '🤝',
  },
];

// Legacy categories for navigation
export const serviceCategories = [
  { id: 'identity', name: 'Identity & Cards', icon: '🪪', description: 'Identity documents' },
  { id: 'certificates', name: 'Certificates', icon: '📜', description: 'All certificates' },
  { id: 'legal', name: 'Legal Services', icon: '⚖️', description: 'Legal documentation' },
  { id: 'business', name: 'Business', icon: '🏢', description: 'Business licenses' },
  { id: 'property', name: 'Property', icon: '🏠', description: 'Property services' },
  { id: 'welfare', name: 'Welfare', icon: '🤝', description: 'Social welfare' },
];

// Form configuration functions
export function getServiceFormFields(slug: string) {
  const config = SERVICE_FORM_CONFIGS[slug];
  
  if (!config) {
    return {
      fields: [
        {
          id: 'fullName',
          name: 'fullName',
          label: 'Full Name',
          type: 'text' as const,
          required: true,
          placeholder: 'Enter your full name',
        },
        {
          id: 'mobileNumber',
          name: 'mobileNumber',
          label: 'Mobile Number',
          type: 'tel' as const,
          required: true,
          placeholder: '10-digit mobile number',
        },
        {
          id: 'email',
          name: 'email',
          label: 'Email Address',
          type: 'email' as const,
          required: false,
          placeholder: 'your.email@example.com',
        },
      ],
      requiredDocuments: [],
    };
  }

  return {
    fields: config.formFields,
    requiredDocuments: config.requiredDocuments,
    complianceNotes: config.complianceNotes,
  };
}