// lib/services.ts
// Updated with finalized single-tier pricing (Professional Consulting)
// Fee structure: Statutory Fee + Professional Fee (+ 18% GST on Prof Fee only)
// ✅ UPDATED: All 91 services with feasibility flags

import { SERVICE_FORM_CONFIGS } from './service-form-configs';

export interface Service {
  // ✅ NEW FEASIBILITY FIELDS
  isFullyOnline?: boolean;
  requiresPhysicalPresence?: boolean;
  requiresSiteInspection?: boolean;
  isStatutoryFeeVariable?: boolean;
  statutoryFeeNote?: string;
  operationalComplexity?: 'low' | 'medium' | 'high';

  id: string;
  slug: string;
  name: string;
  description: string;
  category: string;
  categoryGroup: string;
  
  // Pricing (all in ₹)
  statutoryFee: number;      // Government fee (no GST)
  professionalFee: number;   // Our fee (before GST)
  gst: number;               // 18% of professional fee
  totalPayable: number;      // Total = statutory + professional + GST
  price: number;             // Alias for totalPayable (for compatibility)
  
  // Legacy fields for compatibility
  fee: string;               // For display: professional fee as string
  governmentFee: string;     // For display: statutory fee as string
  
  processingTime: string;
  requiredDocuments: string[];
  popular?: boolean;
  comingSoon?: boolean;
}

export const SERVICES: Service[] = [
  // ========================================
  // IDENTITY & CARDS (14 Services)
  // ========================================

  {
    id: 'IDC-001',
    slug: 'aadhaar-enrollment-support',
    name: 'Aadhaar Enrollment Support',
    description: 'Professional assistance for Aadhaar enrollment, updates, or corrections. Includes form filling, document verification, and appointment booking. Note: You must visit Aadhaar Seva Kendra for biometric capture.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 0,
    professionalFee: 299,
    gst: 53.82,
    totalPayable: 352.82,
    price: 352.82,
    fee: '299',
    governmentFee: 'Free',
    processingTime: '15-30 days',
    requiredDocuments: ['Proof of Identity', 'Proof of Address', 'Date of Birth Proof', 'Photograph'],
    popular: true,
    requiresPhysicalPresence: true,
    isFullyOnline: false,
    operationalComplexity: 'low',
  },

  {
    id: 'IDC-002',
    slug: 'pan-card',
    name: 'PAN Card Application',
    description: 'Fast PAN card application with instant e-PAN for Aadhaar-linked applications. Completely online process with doorstep delivery.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 110,
    professionalFee: 399,
    gst: 71.82,
    totalPayable: 580.82,
    price: 580.82,
    fee: '399',
    governmentFee: '₹110',
    processingTime: '7-15 days',
    requiredDocuments: ['Aadhaar Card', 'Photograph', 'Signature', 'Date of Birth Proof'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'IDC-003',
    slug: 'passport-application-support',
    name: 'Passport Application Support',
    description: 'Complete assistance for new passport, renewal, or re-issue. Includes application filing, fee payment, and appointment booking. Note: You must visit Passport Seva Kendra for biometrics and interview.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 1500,
    professionalFee: 799,
    gst: 143.82,
    totalPayable: 2442.82,
    price: 2442.82,
    fee: '799',
    governmentFee: '₹1,500',
    processingTime: '30-45 days',
    requiredDocuments: ['Birth Certificate', 'Address Proof', 'Identity Proof', 'Passport Photos'],
    popular: true,
    requiresPhysicalPresence: true,
    isFullyOnline: false,
    operationalComplexity: 'medium',
  },

  {
    id: 'IDC-101',
    slug: 'voter-id-card-support',
    name: 'Voter ID Card Application Support',
    description: 'Complete voter ID application assistance with BLO coordination and form filing. Note: BLO may visit for verification or you may need to visit office.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 0,
    professionalFee: 499,
    gst: 89.82,
    totalPayable: 588.82,
    price: 588.82,
    fee: '499',
    governmentFee: 'Free',
    processingTime: '30-60 days',
    requiredDocuments: ['Address Proof', 'Age Proof', 'Photograph', 'Aadhaar Card'],
    popular: true,
    requiresPhysicalPresence: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'IDC-102',
    slug: 'driving-license-support',
    name: 'Driving License Application Support',
    description: 'Complete support for learner license, permanent license, renewal, and duplicate DL. Note: You must visit RTO for written/driving test.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 200,
    professionalFee: 1299,
    gst: 234,
    totalPayable: 1733,
    price: 1733,
    fee: '1299',
    governmentFee: '₹200',
    processingTime: '30-45 days',
    requiredDocuments: ['Aadhaar Card', 'Address Proof', 'Age Proof', 'Photos', 'Medical Certificate', 'Learner License (for permanent)'],
    popular: true,
    requiresPhysicalPresence: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'IDC-103',
    slug: 'ration-card',
    name: 'Ration Card Application',
    description: 'New ration card application or updates with civil supplies department coordination.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 0,
    professionalFee: 599,
    gst: 107.82,
    totalPayable: 706.82,
    price: 706.82,
    fee: '599',
    governmentFee: 'Free',
    processingTime: '45-60 days',
    requiredDocuments: ['Family Members List', 'Address Proof', 'Income Certificate', 'Aadhaar (All members)'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'IDC-104',
    slug: 'birth-certificate',
    name: 'Birth Certificate',
    description: 'Birth certificate application or correction with municipal corporation coordination.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 50,
    professionalFee: 399,
    gst: 71.82,
    totalPayable: 520.82,
    price: 520.82,
    fee: '399',
    governmentFee: '₹50',
    processingTime: '15-30 days',
    requiredDocuments: ['Hospital Birth Certificate', 'Parents ID', 'Address Proof'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'IDC-105',
    slug: 'death-certificate',
    name: 'Death Certificate',
    description: 'Death certificate application with municipal coordination.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 50,
    professionalFee: 399,
    gst: 71.82,
    totalPayable: 520.82,
    price: 520.82,
    fee: '399',
    governmentFee: '₹50',
    processingTime: '15-30 days',
    requiredDocuments: ['Hospital Death Certificate', 'Deceased ID', 'Applicant ID'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'IDC-106',
    slug: 'caste-certificate',
    name: 'Caste Certificate',
    description: 'Official caste certificate for SC/ST/OBC categories with Tahsildar office coordination.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 20,
    professionalFee: 499,
    gst: 89.82,
    totalPayable: 608.82,
    price: 608.82,
    fee: '499',
    governmentFee: '₹20',
    processingTime: '30-45 days',
    requiredDocuments: ['Aadhaar', 'Community Proof', 'School Certificate', 'Address Proof'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'IDC-107',
    slug: 'income-certificate',
    name: 'Income Certificate',
    description: 'Annual income certificate for scholarships, loans, and government schemes.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 20,
    professionalFee: 340,
    gst: 61.20,
    totalPayable: 421.20,
    price: 421.20,
    fee: '340',
    governmentFee: '₹20',
    processingTime: '15-30 days',
    requiredDocuments: ['Aadhaar', 'Salary Slips/Income Proof', 'Address Proof', 'Bank Statement'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'IDC-108',
    slug: 'residence-certificate',
    name: 'Residence/Domicile Certificate',
    description: 'Proof of residence certificate for education and employment.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 20,
    professionalFee: 340,
    gst: 61.20,
    totalPayable: 421.20,
    price: 421.20,
    fee: '340',
    governmentFee: '₹20',
    processingTime: '15-30 days',
    requiredDocuments: ['Aadhaar', 'Address Proof (10+ years)', 'School Certificate', 'Property Documents'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'IDC-109',
    slug: 'disability-certificate',
    name: 'Disability Certificate',
    description: 'Differently abled certificate with medical board coordination. Note: Medical board examination required.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 0,
    professionalFee: 799,
    gst: 143.82,
    totalPayable: 942.82,
    price: 942.82,
    fee: '799',
    governmentFee: 'Free',
    processingTime: '30-60 days',
    requiredDocuments: ['Medical Reports', 'Aadhaar', 'Photographs', 'Medical Board Appointment'],
    popular: false,
    requiresPhysicalPresence: true,
    operationalComplexity: 'high',
  },

  {
    id: 'IDC-110',
    slug: 'senior-citizen-card',
    name: 'Senior Citizen Card',
    description: 'Senior citizen identification card for travel and government benefits.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 0,
    professionalFee: 299,
    gst: 53.82,
    totalPayable: 352.82,
    price: 352.82,
    fee: '299',
    governmentFee: 'Free',
    processingTime: '15-30 days',
    requiredDocuments: ['Age Proof (60+ years)', 'Aadhaar', 'Photograph', 'Address Proof'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'IDC-111',
    slug: 'name-change-gazette',
    name: 'Name Change Gazette',
    description: 'Legal name change through government gazette publication.',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 500,
    professionalFee: 2999,
    gst: 540,
    totalPayable: 4039,
    price: 4039,
    fee: '2999',
    governmentFee: '₹500',
    processingTime: '45-60 days',
    requiredDocuments: ['Affidavit', 'Newspaper Advertisement', 'Aadhaar', 'Gazette Application'],
    popular: false,
    isFullyOnline: false,
    operationalComplexity: 'high',
  },

  // ========================================
  // REVENUE CERTIFICATES (10 Services)
  // ========================================

  {
    id: 'REV-001',
    slug: 'community-certificate',
    name: 'Community Certificate',
    description: 'Official community/caste certificate from Tahsildar.',
    category: 'certificates',
    categoryGroup: 'Student & Education Solutions',
    statutoryFee: 20,
    professionalFee: 340,
    gst: 61.20,
    totalPayable: 421.20,
    price: 421.20,
    fee: '340',
    governmentFee: '₹20',
    processingTime: '30-45 days',
    requiredDocuments: ['Aadhaar', 'Community Proof', 'School Certificate', 'Address Proof'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'REV-002',
    slug: 'income-certificate-revenue',
    name: 'Income Certificate',
    description: 'Annual income certificate for government schemes.',
    category: 'certificates',
    categoryGroup: 'Student & Education Solutions',
    statutoryFee: 20,
    professionalFee: 340,
    gst: 61.20,
    totalPayable: 421.20,
    price: 421.20,
    fee: '340',
    governmentFee: '₹20',
    processingTime: '15-30 days',
    requiredDocuments: ['Aadhaar', 'Income Proof', 'Address Proof', 'Bank Statement'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'REV-003',
    slug: 'nativity-certificate',
    name: 'Nativity Certificate',
    description: 'Birth place certificate from Tahsildar office.',
    category: 'certificates',
    categoryGroup: 'Student & Education Solutions',
    statutoryFee: 20,
    professionalFee: 340,
    gst: 61.20,
    totalPayable: 421.20,
    price: 421.20,
    fee: '340',
    governmentFee: '₹20',
    processingTime: '15-30 days',
    requiredDocuments: ['Birth Certificate', 'School Certificate', 'Address Proof', 'Aadhaar'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'REV-004',
    slug: 'first-graduate-certificate',
    name: 'First Graduate Certificate',
    description: 'Certificate for students who are first in family to pursue higher education.',
    category: 'certificates',
    categoryGroup: 'Student & Education Solutions',
    statutoryFee: 60,
    professionalFee: 590,
    gst: 106.20,
    totalPayable: 756.20,
    price: 756.20,
    fee: '590',
    governmentFee: '₹60',
    processingTime: '30-45 days',
    requiredDocuments: ['Educational Certificates of Parents', 'Family Details', 'Ration Card', 'Self-Declaration'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'REV-114',
    slug: 'legal-heir-certificate',
    name: 'Legal Heir Certificate',
    description: 'Official legal heir certificate from revenue department.',
    category: 'legal',
    categoryGroup: 'Personal & Family Solutions',
    statutoryFee: 50,
    professionalFee: 1999,
    gst: 360,
    totalPayable: 2409,
    price: 2409,
    fee: '1999',
    governmentFee: '₹50',
    processingTime: '30-60 days',
    requiredDocuments: ['Death Certificate', 'Family Details', 'Ration Card', 'Property Details'],
    popular: false,
    operationalComplexity: 'high',
  },

  {
    id: 'REV-201',
    slug: 'widow-certificate',
    name: 'Widow Certificate',
    description: 'Widow certificate for pension schemes and government benefits.',
    category: 'certificates',
    categoryGroup: 'Personal & Family Solutions',
    statutoryFee: 60,
    professionalFee: 390,
    gst: 70.20,
    totalPayable: 520.20,
    price: 520.20,
    fee: '390',
    governmentFee: '₹60',
    processingTime: '30-45 days',
    requiredDocuments: ['Death Certificate (Husband)', 'Marriage Certificate', 'Identity Proof', 'Income Certificate'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'REV-202',
    slug: 'deserted-woman-certificate',
    name: 'Deserted Woman Certificate',
    description: 'Certificate for deserted women to access government welfare schemes.',
    category: 'certificates',
    categoryGroup: 'Personal & Family Solutions',
    statutoryFee: 60,
    professionalFee: 540,
    gst: 97.20,
    totalPayable: 697.20,
    price: 697.20,
    fee: '540',
    governmentFee: '₹60',
    processingTime: '45-60 days',
    requiredDocuments: ['Marriage Certificate', 'Proof of Desertion', 'Identity Proof', 'Income Certificate'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'REV-301',
    slug: 'patta-transfer-full-field',
    name: 'Patta Transfer (Full Field)',
    description: 'Complete patta transfer with revenue records update. Our team coordinates with VAO/Taluk office.',
    category: 'property',
    categoryGroup: 'Property & Asset Solutions',
    statutoryFee: 60,
    professionalFee: 840,
    gst: 151.20,
    totalPayable: 1051.20,
    price: 1051.20,
    fee: '840',
    governmentFee: '₹60',
    processingTime: '60-90 days',
    requiredDocuments: ['Registered Sale Deed', 'Old Patta', 'Survey Documents', 'Encumbrance Certificate'],
    popular: true,
    operationalComplexity: 'high',
  },

  {
    id: 'REV-302',
    slug: 'patta-transfer-subdivision',
    name: 'Patta Transfer (Subdivision)',
    description: 'Patta transfer for subdivided land parcels with survey coordination.',
    category: 'property',
    categoryGroup: 'Property & Asset Solutions',
    statutoryFee: 60,
    professionalFee: 1499,
    gst: 270,
    totalPayable: 1829,
    price: 1829,
    fee: '1499',
    governmentFee: '₹60',
    processingTime: '60-90 days',
    requiredDocuments: ['Sale Deed', 'Subdivision Map', 'Survey Documents', 'Old Patta', 'Encumbrance Certificate'],
    popular: false,
    operationalComplexity: 'high',
  },

  {
    id: 'REV-402',
    slug: 'money-lender-license',
    name: "Money Lender's License",
    description: 'Official license for conducting money lending business operations.',
    category: 'business',
    categoryGroup: 'Business & Licensing Solutions',
    statutoryFee: 60,
    professionalFee: 1940,
    gst: 349.20,
    totalPayable: 2349.20,
    price: 2349.20,
    fee: '1940',
    governmentFee: '₹60',
    processingTime: '60-90 days',
    requiredDocuments: ['Business Registration', 'Identity Proof', 'PAN Card', 'Financial Statements', 'Character Certificate'],
    popular: false,
    isFullyOnline: false,
    operationalComplexity: 'high',
  },

  // ========================================
  // WELFARE SCHEMES (17 Services)
  // ========================================

  {
    id: 'REV-501',
    slug: 'old-age-pension',
    name: 'Old Age Pension (OAP)',
    description: 'Monthly pension scheme for senior citizens.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 60,
    professionalFee: 439,
    gst: 79.02,
    totalPayable: 618.02,
    price: 618.02,
    fee: '439',
    governmentFee: '₹60',
    processingTime: '45-60 days',
    requiredDocuments: ['Age Proof', 'Income Certificate', 'Bank Account', 'Aadhaar', 'Photographs', 'Ration Card'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'REV-502',
    slug: 'widow-pension',
    name: 'Destitute Widow Pension',
    description: 'Monthly pension for widows below poverty line.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 60,
    professionalFee: 439,
    gst: 79.02,
    totalPayable: 618.02,
    price: 618.02,
    fee: '439',
    governmentFee: '₹60',
    processingTime: '45-60 days',
    requiredDocuments: ['Death Certificate (Husband)', 'Income Certificate', 'Age Proof', 'Bank Account', 'Aadhaar'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'REV-503',
    slug: 'girl-child-protection',
    name: 'Girl Child Protection Scheme',
    description: 'Government scheme for girl child education and welfare.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 100,
    professionalFee: 650,
    gst: 117,
    totalPayable: 867,
    price: 867,
    fee: '650',
    governmentFee: '₹100',
    processingTime: '30-60 days',
    requiredDocuments: ['Birth Certificate (Girl)', 'Income Certificate', 'Ration Card', 'Bank Account', 'School Certificate'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'WEL-009',
    slug: 'free-bicycle-scheme',
    name: 'Free Bicycle Scheme',
    description: 'Free bicycle for school students.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 499,
    gst: 89.82,
    totalPayable: 588.82,
    price: 588.82,
    fee: '499',
    governmentFee: 'Free',
    processingTime: '30-60 days',
    requiredDocuments: ['School ID', 'Bonafide Certificate', 'Aadhaar', 'Income Certificate'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'WEL-010',
    slug: 'free-laptop-scheme',
    name: 'Free Laptop Scheme',
    description: 'Free laptop for meritorious students.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 699,
    gst: 125.82,
    totalPayable: 824.82,
    price: 824.82,
    fee: '699',
    governmentFee: 'Free',
    processingTime: '60-90 days',
    requiredDocuments: ['Mark Sheets', 'School Certificate', 'Aadhaar', 'Income Certificate'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'WEL-013',
    slug: 'sc-st-scholarship',
    name: 'SC/ST Scholarship',
    description: 'Educational scholarship for SC/ST students.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 799,
    gst: 143.82,
    totalPayable: 942.82,
    price: 942.82,
    fee: '799',
    governmentFee: 'Free',
    processingTime: '60-90 days',
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Mark Sheets', 'College ID', 'Bank Account'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'WEL-014',
    slug: 'bc-mbc-scholarship',
    name: 'BC/MBC Scholarship',
    description: 'Educational scholarship for BC/MBC students.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 799,
    gst: 143.82,
    totalPayable: 942.82,
    price: 942.82,
    fee: '799',
    governmentFee: 'Free',
    processingTime: '60-90 days',
    requiredDocuments: ['Community Certificate', 'Income Certificate', 'Mark Sheets', 'College ID', 'Bank Account'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'WEL-015',
    slug: 'minority-scholarship',
    name: 'Minority Scholarship',
    description: 'Educational scholarship for minority community students.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 799,
    gst: 143.82,
    totalPayable: 942.82,
    price: 942.82,
    fee: '799',
    governmentFee: 'Free',
    processingTime: '60-90 days',
    requiredDocuments: ['Community Certificate', 'Income Certificate', 'Mark Sheets', 'College ID', 'Bank Account'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'WEL-017',
    slug: 'bonafide-certificate',
    name: 'Bonafide Certificate',
    description: 'School/college bonafide certificate for various purposes.',
    category: 'welfare',
    categoryGroup: 'Student & Education Solutions',
    statutoryFee: 0,
    professionalFee: 299,
    gst: 53.82,
    totalPayable: 352.82,
    price: 352.82,
    fee: '299',
    governmentFee: 'Free',
    processingTime: '7-15 days',
    requiredDocuments: ['Student ID', 'Purpose Letter', 'Attendance Proof'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  // Add remaining 13 welfare services (WEL-001 through WEL-008, WEL-011, WEL-012, WEL-016)
  {
    id: 'WEL-001',
    slug: 'old-age-pension-alt',
    name: 'Old Age Pension',
    description: 'Monthly pension for senior citizens above 60 years.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 599,
    gst: 107.82,
    totalPayable: 706.82,
    price: 706.82,
    fee: '599',
    governmentFee: 'Free',
    processingTime: '30-60 days',
    requiredDocuments: ['Age Proof (60+)', 'Aadhaar', 'Bank Account', 'Income Certificate', 'Address Proof'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'WEL-002',
    slug: 'widow-pension-alt',
    name: 'Widow Pension',
    description: 'Monthly pension for widows below poverty line.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 599,
    gst: 107.82,
    totalPayable: 706.82,
    price: 706.82,
    fee: '599',
    governmentFee: 'Free',
    processingTime: '30-60 days',
    requiredDocuments: ['Death Certificate (Spouse)', 'Income Certificate', 'Aadhaar', 'Bank Account'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'WEL-003',
    slug: 'disability-pension',
    name: 'Disability Pension',
    description: 'Monthly pension for differently abled persons.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 699,
    gst: 125.82,
    totalPayable: 824.82,
    price: 824.82,
    fee: '699',
    governmentFee: 'Free',
    processingTime: '30-60 days',
    requiredDocuments: ['Disability Certificate (40%+)', 'Income Certificate', 'Aadhaar', 'Bank Account'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'WEL-004',
    slug: 'pm-awas-yojana',
    name: 'PM Awas Yojana (Housing)',
    description: 'Central government housing subsidy for first-time home buyers.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 999,
    gst: 179.82,
    totalPayable: 1178.82,
    price: 1178.82,
    fee: '999',
    governmentFee: 'Free',
    processingTime: '45-90 days',
    requiredDocuments: ['Income Proof', 'Property Details', 'Aadhaar', 'Bank Account', 'Caste Certificate'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'WEL-005',
    slug: 'ration-card-apl-bpl',
    name: 'Ration Card (APL/BPL)',
    description: 'Application for subsidized food grains under PDS.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 599,
    gst: 107.82,
    totalPayable: 706.82,
    price: 706.82,
    fee: '599',
    governmentFee: 'Free',
    processingTime: '30-60 days',
    requiredDocuments: ['Family Members List', 'Income Certificate', 'Address Proof', 'Aadhaar (All)'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'WEL-006',
    slug: 'marriage-assistance',
    name: 'Marriage Assistance Scheme',
    description: 'Financial assistance for poor families for daughter marriage.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 799,
    gst: 143.82,
    totalPayable: 942.82,
    price: 942.82,
    fee: '799',
    governmentFee: 'Free',
    processingTime: '45-90 days',
    requiredDocuments: ['Income Certificate', 'Marriage Card', 'Caste Certificate', 'Bank Account', 'Aadhaar'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'WEL-007',
    slug: 'maternity-benefit',
    name: 'Maternity Benefit Scheme',
    description: 'Financial assistance for pregnant women under PMMVY.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 699,
    gst: 125.82,
    totalPayable: 824.82,
    price: 824.82,
    fee: '699',
    governmentFee: 'Free',
    processingTime: '30-60 days',
    requiredDocuments: ['Pregnancy Certificate', 'Aadhaar', 'Bank Account', 'Hospital Records'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'WEL-008',
    slug: 'education-loan',
    name: 'Education Loan Assistance',
    description: 'Guidance for education loan under government schemes.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 999,
    gst: 179.82,
    totalPayable: 1178.82,
    price: 1178.82,
    fee: '999',
    governmentFee: 'Free',
    processingTime: '30-45 days',
    requiredDocuments: ['Admission Letter', 'Fee Structure', 'Income Certificate', 'Bank Statements', 'Collateral'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'WEL-011',
    slug: 'unemployment-allowance',
    name: 'Unemployment Allowance',
    description: 'Monthly allowance for educated unemployed youth.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 699,
    gst: 125.82,
    totalPayable: 824.82,
    price: 824.82,
    fee: '699',
    governmentFee: 'Free',
    processingTime: '45-60 days',
    requiredDocuments: ['Education Certificates', 'Employment Exchange Registration', 'Income Certificate', 'Aadhaar', 'Bank Account'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'WEL-012',
    slug: 'agricultural-loan',
    name: 'Agricultural Loan (Kisan Credit Card)',
    description: 'Credit facility for farmers for agriculture needs.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 999,
    gst: 179.82,
    totalPayable: 1178.82,
    price: 1178.82,
    fee: '999',
    governmentFee: 'Free',
    processingTime: '30-45 days',
    requiredDocuments: ['Land Documents', 'Patta/Chitta', 'Aadhaar', 'Bank Account', 'Crop Details'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'WEL-016',
    slug: 'ayushman-bharat',
    name: 'Ayushman Bharat (Health Insurance)',
    description: 'Free health insurance up to ₹5 lakhs for poor families.',
    category: 'welfare',
    categoryGroup: 'Social & Pension Schemes',
    statutoryFee: 0,
    professionalFee: 699,
    gst: 125.82,
    totalPayable: 824.82,
    price: 824.82,
    fee: '699',
    governmentFee: 'Free',
    processingTime: '30-45 days',
    requiredDocuments: ['Aadhaar (Family)', 'Ration Card', 'Income Certificate', 'Family Details'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  // ========================================
  // BUSINESS & LICENSES (17 Services)
  // ========================================

  {
    id: 'BUS-001',
    slug: 'shop-establishment-registration',
    name: 'Shop & Establishment Registration',
    description: 'Mandatory registration for all commercial establishments.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 500,
    professionalFee: 1999,
    gst: 360,
    totalPayable: 2859,
    price: 2859,
    fee: '1999',
    governmentFee: '₹500',
    processingTime: '15-30 days',
    requiredDocuments: ['Business Address Proof', 'Owner ID', 'PAN Card', 'Trade License'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'BUS-002',
    slug: 'food-license-fssai',
    name: 'Food License (FSSAI)',
    description: 'Complete FSSAI registration for food businesses. Online application with digital certificate.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 100,
    professionalFee: 2999,
    gst: 540,
    totalPayable: 3639,
    price: 3639,
    fee: '2999',
    governmentFee: '₹100',
    processingTime: '30-45 days',
    requiredDocuments: ['Business PAN', 'Shop Proof', 'Aadhaar', 'Bank Details', 'Food Safety Plan'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'BUS-003',
    slug: 'trade-license',
    name: 'Trade License',
    description: 'Municipal corporation trade license for commercial activities.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 1000,
    professionalFee: 2499,
    gst: 450,
    totalPayable: 3949,
    price: 3949,
    fee: '2499',
    governmentFee: '₹1,000',
    processingTime: '30-45 days',
    requiredDocuments: ['Business Address Proof', 'Owner ID', 'Building Plan', 'NOCs'],
    popular: true,
    isFullyOnline: false,
    operationalComplexity: 'medium',
  },

  {
    id: 'BUS-004',
    slug: 'factory-license',
    name: 'Factory License',
    description: 'Factory registration under Factories Act. Note: Site inspection required.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 2000,
    professionalFee: 9999,
    gst: 1800,
    totalPayable: 13799,
    price: 13799,
    fee: '9999',
    governmentFee: '₹2,000',
    processingTime: '60-90 days',
    requiredDocuments: ['Building Plan', 'Machinery Details', 'Fire NOC', 'Power Connection', 'Employee List'],
    popular: false,
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  {
    id: 'BUS-005',
    slug: 'msme-udyam-registration',
    name: 'MSME / Udyam Registration',
    description: 'Fast Udyam registration with government benefits. Completely online process.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 0,
    professionalFee: 1999,
    gst: 360,
    totalPayable: 2359,
    price: 2359,
    fee: '1999',
    governmentFee: 'Free',
    processingTime: '7-15 days',
    requiredDocuments: ['Aadhaar', 'PAN Card', 'Business Address', 'Bank Details', 'Investment Details'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'BUS-006',
    slug: 'gst-registration',
    name: 'GST Registration',
    description: 'Comprehensive GST registration with GSTIN activation. Completely online process.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 0,
    professionalFee: 2999,
    gst: 540,
    totalPayable: 3539,
    price: 3539,
    fee: '2999',
    governmentFee: 'Free',
    processingTime: '15-30 days',
    requiredDocuments: ['PAN Card', 'Aadhaar', 'Business Address Proof', 'Bank Details', 'Digital Signature'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'BUS-007',
    slug: 'professional-tax-registration',
    name: 'Professional Tax Registration',
    description: 'Professional tax enrollment. Online registration.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 0,
    professionalFee: 1499,
    gst: 270,
    totalPayable: 1769,
    price: 1769,
    fee: '1499',
    governmentFee: 'Free',
    processingTime: '15-30 days',
    requiredDocuments: ['Business Registration', 'Employee List', 'PAN Card', 'Address Proof'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'BUS-008',
    slug: 'import-export-code',
    name: 'Import Export Code (IEC)',
    description: 'IEC registration for international trade. Online process.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 0,
    professionalFee: 2999,
    gst: 540,
    totalPayable: 3539,
    price: 3539,
    fee: '2999',
    governmentFee: 'Free',
    processingTime: '15-30 days',
    requiredDocuments: ['PAN Card', 'Bank Certificate', 'Business Address', 'Digital Signature'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'BUS-009',
    slug: 'iso-certification',
    name: 'ISO Certification',
    description: 'ISO 9001:2015 certification with audit support.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 15000,
    professionalFee: 19999,
    gst: 3600,
    totalPayable: 38599,
    price: 38599,
    fee: '19999',
    governmentFee: '₹15,000',
    processingTime: '60-90 days',
    requiredDocuments: ['Company Details', 'Process Documentation', 'Quality Manual', 'Employee Training Records'],
    popular: false,
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  {
    id: 'BUS-010',
    slug: 'liquor-license-consultation',
    name: 'Liquor License Application Support',
    description: 'Complete liquor license application support with TASMAC coordination. Note: License fees (₹1L+) paid separately.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 0,
    professionalFee: 19999,
    gst: 3600,
    totalPayable: 23599,
    price: 23599,
    fee: '19999',
    governmentFee: '₹1,00,000 - ₹10,00,000',
    processingTime: '60-90 days',
    requiredDocuments: ['Building Plan', 'Fire NOC', 'Health NOC', 'Police NOC', 'Business Plan', 'Financial Statements'],
    popular: false,
    isStatutoryFeeVariable: true,
    statutoryFeeNote: 'License fee: ₹1,00,000 to ₹10,00,000 depending on location and type. Security deposit: ₹50,000 to ₹5,00,000. Payable directly to TASMAC.',
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  {
    id: 'BUS-011',
    slug: 'explosive-license',
    name: 'Explosive License',
    description: 'License for handling explosives. Note: Site inspection required.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 0,
    professionalFee: 14999,
    gst: 2700,
    totalPayable: 17699,
    price: 17699,
    fee: '14999',
    governmentFee: '₹10,000 - ₹50,000',
    processingTime: '90-120 days',
    requiredDocuments: ['Site Plan', 'Safety Measures', 'Storage Details', 'Fire NOC', 'Police Verification'],
    popular: false,
    isStatutoryFeeVariable: true,
    statutoryFeeNote: 'License fee varies from ₹10,000 to ₹50,000 based on quantity and type. Inspection fee additional.',
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  {
    id: 'BUS-012',
    slug: 'arms-license',
    name: 'Arms License',
    description: 'Firearm license with police verification. Note: Physical verification required.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 3000,
    professionalFee: 9999,
    gst: 1800,
    totalPayable: 14799,
    price: 14799,
    fee: '9999',
    governmentFee: '₹3,000',
    processingTime: '120-180 days',
    requiredDocuments: ['Identity Proof', 'Address Proof', 'Character Certificate', 'Threat Proof', 'Medical Certificate'],
    popular: false,
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  {
    id: 'BUS-013',
    slug: 'hotel-license',
    name: 'Hotel License',
    description: 'Hotel registration with tourism and health department. Note: Site inspection required.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 5000,
    professionalFee: 7999,
    gst: 1440,
    totalPayable: 14439,
    price: 14439,
    fee: '7999',
    governmentFee: '₹5,000',
    processingTime: '45-60 days',
    requiredDocuments: ['Building Plan', 'Fire NOC', 'Health License', 'Trade License', 'Police NOC'],
    popular: false,
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  {
    id: 'BUS-014',
    slug: 'restaurant-license',
    name: 'Restaurant License',
    description: 'Restaurant license with health department. Note: Site visit required.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 2000,
    professionalFee: 4999,
    gst: 900,
    totalPayable: 7899,
    price: 7899,
    fee: '4999',
    governmentFee: '₹2,000',
    processingTime: '30-45 days',
    requiredDocuments: ['FSSAI License', 'Fire NOC', 'Health NOC', 'Trade License', 'Water Test Report'],
    popular: true,
    requiresSiteInspection: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'BUS-015',
    slug: 'medical-shop-license',
    name: 'Medical Shop License',
    description: 'Drug license for pharmacy. Note: Inspection required.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 5000,
    professionalFee: 6999,
    gst: 1260,
    totalPayable: 13259,
    price: 13259,
    fee: '6999',
    governmentFee: '₹5,000',
    processingTime: '45-60 days',
    requiredDocuments: ['Pharmacy Degree', 'Shop Layout', 'Storage Facilities', 'Trade License'],
    popular: false,
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  {
    id: 'BUS-016',
    slug: 'petrol-bunk-license',
    name: 'Petrol Bunk License',
    description: 'Petroleum dealership license. Note: High statutory fees vary by location.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 0,
    professionalFee: 49999,
    gst: 9000,
    totalPayable: 58999,
    price: 58999,
    fee: '49999',
    governmentFee: '₹5,00,000 - ₹20,00,000',
    processingTime: '180-360 days',
    requiredDocuments: ['Land Documents', 'NOCs (Multiple)', 'Financial Proof', 'Business Plan'],
    popular: false,
    isStatutoryFeeVariable: true,
    statutoryFeeNote: 'Dealership security deposit: ₹5,00,000 to ₹20,00,000. License fees vary by location and fuel type.',
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  {
    id: 'BUS-017',
    slug: 'ssi-registration',
    name: 'SSI Registration',
    description: 'Small scale industry registration. Online process.',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 0,
    professionalFee: 2999,
    gst: 540,
    totalPayable: 3539,
    price: 3539,
    fee: '2999',
    governmentFee: 'Free',
    processingTime: '15-30 days',
    requiredDocuments: ['Business Registration', 'Investment Proof', 'Machinery Details', 'Bank Statement'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'COC-401',
    slug: 'trade-license-chennai',
    name: 'Trade License (Chennai Corporation)',
    description: 'Chennai corporation trade license for commercial activities.',
    category: 'business',
    categoryGroup: 'Business & Licensing Solutions',
    statutoryFee: 1000,
    professionalFee: 2499,
    gst: 450,
    totalPayable: 3949,
    price: 3949,
    fee: '2499',
    governmentFee: '₹1,000',
    processingTime: '30-45 days',
    requiredDocuments: ['Business Address Proof', 'Owner ID', 'Building Plan', 'NOCs'],
    popular: true,
    isFullyOnline: false,
    operationalComplexity: 'medium',
  },

  {
    id: 'DFR-103',
    slug: 'fire-noc',
    name: 'Fire NOC (Non-Multi Storeyed)',
    description: 'Fire department NOC for commercial buildings. Note: Site inspection required.',
    category: 'business',
    categoryGroup: 'Business & Licensing Solutions',
    statutoryFee: 15,
    professionalFee: 4985,
    gst: 897.30,
    totalPayable: 5897.30,
    price: 5897.30,
    fee: '4985',
    governmentFee: '₹15',
    processingTime: '45-60 days',
    requiredDocuments: ['Building Plan', 'Fire Safety Equipment', 'Site Plan', 'Trade License'],
    popular: true,
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  // ========================================
  // PROPERTY & ASSETS (11 Services)
  // ========================================

  {
    id: 'PRP-001',
    slug: 'encumbrance-certificate',
    name: 'Encumbrance Certificate',
    description: 'Property transaction history certificate from sub-registrar office.',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 75,
    professionalFee: 499,
    gst: 89.82,
    totalPayable: 663.82,
    price: 663.82,
    fee: '499',
    governmentFee: '₹75',
    processingTime: '7-15 days',
    requiredDocuments: ['Property Address', 'Survey Number', 'Owner Details', 'Period Required'],
    popular: true,
    isFullyOnline: false,
    operationalComplexity: 'medium',
  },

  {
    id: 'PRP-002',
    slug: 'patta-mutation',
    name: 'Patta Mutation',
    description: 'Transfer of land records post sale. Our team coordinates with VAO/Taluk office.',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 60,
    professionalFee: 840,
    gst: 151.20,
    totalPayable: 1051.20,
    price: 1051.20,
    fee: '840',
    governmentFee: '₹60',
    processingTime: '60-90 days',
    requiredDocuments: ['Registered Sale Deed', 'Old Patta', 'Survey Documents', 'Encumbrance Certificate'],
    popular: true,
    operationalComplexity: 'high',
  },

  {
    id: 'PRP-003',
    slug: 'land-conversion',
    name: 'Land Conversion (Agricultural to Non-Agricultural)',
    description: 'Expert assistance for land use conversion with DTCP approval. Government fees vary by land size and calculated separately.',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 0,
    professionalFee: 9999,
    gst: 1800,
    totalPayable: 11799,
    price: 11799,
    fee: '9999',
    governmentFee: 'At Actuals',
    processingTime: '90-180 days',
    requiredDocuments: ['Original Patta and Chitta', 'Survey Map', 'Encumbrance Certificate', 'Layout Plan', 'DTCP Approval'],
    popular: false,
    isStatutoryFeeVariable: true,
    statutoryFeeNote: 'Government conversion fee: ₹50-₹500 per sq.ft (varies by district). Additional charges: betterment levy, panchayat fees. Total ranges from ₹50,000 to ₹5,00,000.',
    operationalComplexity: 'high',
  },

  {
    id: 'PRP-004',
    slug: 'land-partition',
    name: 'Land Partition (Subdivision)',
    description: 'Legal partition of land among co-owners with survey department coordination.',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 100,
    professionalFee: 7999,
    gst: 1440,
    totalPayable: 9539,
    price: 9539,
    fee: '7999',
    governmentFee: '₹100',
    processingTime: '60-90 days',
    requiredDocuments: ['Original Patta', 'Survey Map', 'Partition Deed', 'Co-owner Consent', 'Layout Plan'],
    popular: false,
    operationalComplexity: 'high',
  },

  {
    id: 'PRP-005',
    slug: 'building-plan-approval',
    name: 'Building Plan Approval',
    description: 'Municipal building plan approval with engineer coordination. Note: Site inspection required.',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 2000,
    professionalFee: 9999,
    gst: 1800,
    totalPayable: 13799,
    price: 13799,
    fee: '9999',
    governmentFee: '₹2,000+',
    processingTime: '45-90 days',
    requiredDocuments: ['Property Documents', 'Survey Map', 'Structural Plan', 'Architect Certificate', 'NOCs'],
    popular: true,
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  {
    id: 'PRP-006',
    slug: 'occupancy-certificate',
    name: 'Occupancy Certificate',
    description: 'Building completion certificate with municipal inspection. Note: Site visit required.',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 1000,
    professionalFee: 7999,
    gst: 1440,
    totalPayable: 10439,
    price: 10439,
    fee: '7999',
    governmentFee: '₹1,000',
    processingTime: '30-60 days',
    requiredDocuments: ['Approved Building Plan', 'Completion Certificate', 'Fire NOC', 'Structural Stability Certificate'],
    popular: false,
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  {
    id: 'PRP-007',
    slug: 'property-tax-payment',
    name: 'Property Tax Payment',
    description: 'Annual property tax payment and arrears clearance with municipal corporation.',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 0,
    professionalFee: 299,
    gst: 53.82,
    totalPayable: 352.82,
    price: 352.82,
    fee: '299',
    governmentFee: 'At Actuals',
    processingTime: '3-7 days',
    requiredDocuments: ['Property Details', 'Previous Tax Receipt', 'Owner ID'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'PRP-008',
    slug: 'land-sale-deed',
    name: 'Land Sale Deed Registration',
    description: 'Complete sale deed preparation and sub-registrar registration.',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 0,
    professionalFee: 4999,
    gst: 900,
    totalPayable: 5899,
    price: 5899,
    fee: '4999',
    governmentFee: 'At Actuals (7% Stamp Duty + 1% Registration)',
    processingTime: '15-30 days',
    requiredDocuments: ['Original Patta', 'Encumbrance Certificate', 'Party IDs', 'Property Documents'],
    popular: true,
    isStatutoryFeeVariable: true,
    statutoryFeeNote: 'Stamp duty: 7% of property value. Registration fee: 1% of property value. Additional charges for rural properties.',
    operationalComplexity: 'medium',
  },

  {
    id: 'PRP-009',
    slug: 'survey-resurvey',
    name: 'Land Survey / Resurvey',
    description: 'Official land measurement with survey department coordination.',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 500,
    professionalFee: 4999,
    gst: 900,
    totalPayable: 6399,
    price: 6399,
    fee: '4999',
    governmentFee: '₹500',
    processingTime: '30-60 days',
    requiredDocuments: ['Patta Copy', 'Old Survey Map', 'Boundary Details', 'Adjacent Owner Details'],
    popular: false,
    operationalComplexity: 'high',
  },

  {
    id: 'PRP-010',
    slug: 'patta-name-correction',
    name: 'Patta Name Correction',
    description: 'Correction of name spelling errors in land records with VAO coordination.',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 30,
    professionalFee: 699,
    gst: 125.82,
    totalPayable: 854.82,
    price: 854.82,
    fee: '699',
    governmentFee: '₹30',
    processingTime: '30-45 days',
    requiredDocuments: ['Patta Copy', 'Correct Identity Proof', 'Affidavit', 'Gazette (if applicable)'],
    popular: false,
    operationalComplexity: 'medium',
  },

  {
    id: 'PRP-011',
    slug: 'land-dispute-resolution',
    name: 'Land Dispute Resolution Support',
    description: 'Legal assistance for land boundary disputes with documentation support.',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 0,
    professionalFee: 14999,
    gst: 2700,
    totalPayable: 17699,
    price: 17699,
    fee: '14999',
    governmentFee: 'Court Fees (Varies)',
    processingTime: '180-365 days',
    requiredDocuments: ['Property Documents', 'Survey Maps', 'Legal Notices', 'Witness Details'],
    popular: false,
    isStatutoryFeeVariable: true,
    statutoryFeeNote: 'Court fees vary based on property value. Legal notice fees additional.',
    operationalComplexity: 'high',
  },

  // ========================================
  // VEHICLE SERVICES (9 Services)
  // ========================================

  {
    id: 'VEH-001',
    slug: 'vehicle-rc-transfer',
    name: 'Vehicle RC Transfer',
    description: 'Transfer of vehicle ownership with RTO coordination.',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 300,
    professionalFee: 1499,
    gst: 270,
    totalPayable: 2069,
    price: 2069,
    fee: '1499',
    governmentFee: '₹300',
    processingTime: '15-30 days',
    requiredDocuments: ['Original RC', 'Insurance Copy', 'Sale Agreement', 'Form 29 & 30', 'PUC Certificate'],
    popular: true,
    isFullyOnline: false,
    operationalComplexity: 'medium',
  },

  {
    id: 'VEH-002',
    slug: 'vehicle-registration',
    name: 'New Vehicle Registration',
    description: 'Fresh vehicle registration for new purchases with RTO.',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 500,
    professionalFee: 1999,
    gst: 360,
    totalPayable: 2859,
    price: 2859,
    fee: '1999',
    governmentFee: '₹500',
    processingTime: '15-30 days',
    requiredDocuments: ['Invoice', 'Insurance', 'Address Proof', 'Form 20 & 21', 'PAN Card'],
    popular: true,
    isFullyOnline: false,
    operationalComplexity: 'medium',
  },

  {
    id: 'VEH-003',
    slug: 'duplicate-rc',
    name: 'Duplicate RC',
    description: 'Duplicate RC for lost/damaged registration certificate.',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 100,
    professionalFee: 799,
    gst: 143.82,
    totalPayable: 1042.82,
    price: 1042.82,
    fee: '799',
    governmentFee: '₹100',
    processingTime: '15-30 days',
    requiredDocuments: ['Vehicle Details', 'Owner ID', 'FIR Copy (if stolen)', 'Address Proof'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'VEH-004',
    slug: 'hypothecation-removal',
    name: 'Hypothecation Removal',
    description: 'Remove loan lien from vehicle RC after loan closure.',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 100,
    professionalFee: 999,
    gst: 179.82,
    totalPayable: 1278.82,
    price: 1278.82,
    fee: '999',
    governmentFee: '₹100',
    processingTime: '15-30 days',
    requiredDocuments: ['Original RC', 'NOC from Bank', 'Form 35', 'Owner ID'],
    popular: true,
    isFullyOnline: false,
    operationalComplexity: 'medium',
  },

  {
    id: 'VEH-005',
    slug: 'noc-vehicle-transfer',
    name: 'Vehicle NOC (Interstate Transfer)',
    description: 'No Objection Certificate for interstate vehicle transfer.',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 200,
    professionalFee: 1299,
    gst: 234,
    totalPayable: 1733,
    price: 1733,
    fee: '1299',
    governmentFee: '₹200',
    processingTime: '15-30 days',
    requiredDocuments: ['Original RC', 'Insurance', 'Pollution Certificate', 'Tax Payment Proof'],
    popular: false,
    isFullyOnline: false,
    operationalComplexity: 'medium',
  },

  {
    id: 'VEH-006',
    slug: 'road-tax-payment',
    name: 'Road Tax Payment',
    description: 'Annual road tax and arrears payment for vehicles.',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 0,
    professionalFee: 299,
    gst: 53.82,
    totalPayable: 352.82,
    price: 352.82,
    fee: '299',
    governmentFee: 'At Actuals',
    processingTime: '3-7 days',
    requiredDocuments: ['RC Copy', 'Previous Tax Receipt', 'Vehicle Details'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
  },

  {
    id: 'VEH-007',
    slug: 'learner-license',
    name: 'Learner License',
    description: 'Learner license application with RTO test booking. Note: Written test required.',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 150,
    professionalFee: 699,
    gst: 125.82,
    totalPayable: 974.82,
    price: 974.82,
    fee: '699',
    governmentFee: '₹150',
    processingTime: '7-15 days',
    requiredDocuments: ['Age Proof', 'Address Proof', 'Medical Certificate (for transport)', 'Photographs'],
    popular: true,
    requiresPhysicalPresence: true,
    operationalComplexity: 'low',
  },

  {
    id: 'VEH-008',
    slug: 'permanent-driving-license',
    name: 'Permanent Driving License',
    description: 'Permanent DL after learner license. Note: Driving test required.',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 200,
    professionalFee: 999,
    gst: 179.82,
    totalPayable: 1378.82,
    price: 1378.82,
    fee: '999',
    governmentFee: '₹200',
    processingTime: '15-30 days',
    requiredDocuments: ['Learner License', 'Address Proof', 'Medical Certificate', 'Test Appointment'],
    popular: true,
    requiresPhysicalPresence: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'VEH-009',
    slug: 'international-driving-permit',
    name: 'International Driving Permit',
    description: 'IDP for driving abroad with RTO coordination.',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 1000,
    professionalFee: 1499,
    gst: 270,
    totalPayable: 2769,
    price: 2769,
    fee: '1499',
    governmentFee: '₹1,000',
    processingTime: '7-15 days',
    requiredDocuments: ['Valid DL', 'Passport', 'Photographs', 'Travel Documents'],
    popular: false,
    requiresPhysicalPresence: true,
    operationalComplexity: 'low',
  },

  // ========================================
  // LEGAL SERVICES (5 Services)
  // ========================================

  {
    id: 'LEG-001',
    slug: 'affidavit-drafting',
    name: 'Affidavit Drafting',
    description: 'Legal affidavit preparation with notary coordination.',
    category: 'legal',
    categoryGroup: 'Legal Services',
    statutoryFee: 50,
    professionalFee: 499,
    gst: 89.82,
    totalPayable: 638.82,
    price: 638.82,
    fee: '499',
    governmentFee: '₹50',
    processingTime: '1-3 days',
    requiredDocuments: ['Purpose Details', 'Supporting Documents', 'ID Proof'],
    popular: true,
    operationalComplexity: 'low',
  },

  {
    id: 'LEG-002',
    slug: 'notary-services',
    name: 'Notary Services',
    description: 'Document notarization and attestation services.',
    category: 'legal',
    categoryGroup: 'Legal Services',
    statutoryFee: 100,
    professionalFee: 299,
    gst: 53.82,
    totalPayable: 452.82,
    price: 452.82,
    fee: '299',
    governmentFee: '₹100',
    processingTime: '1-2 days',
    requiredDocuments: ['Original Documents', 'ID Proof', 'Photographs'],
    popular: true,
    operationalComplexity: 'low',
  },

  {
    id: 'LEG-003',
    slug: 'power-of-attorney',
    name: 'Power of Attorney',
    description: 'POA preparation and registration with sub-registrar.',
    category: 'legal',
    categoryGroup: 'Legal Services',
    statutoryFee: 500,
    professionalFee: 1999,
    gst: 360,
    totalPayable: 2859,
    price: 2859,
    fee: '1999',
    governmentFee: '₹500',
    processingTime: '7-15 days',
    requiredDocuments: ['Grantor & Grantee IDs', 'Purpose Details', 'Witnesses'],
    popular: false,
    operationalComplexity: 'medium',
  },

  {
    id: 'LEG-004',
    slug: 'legal-heir-certificate-legal',
    name: 'Legal Heir Certificate',
    description: 'Official legal heir certificate from Tahsildar office.',
    category: 'legal',
    categoryGroup: 'Legal Services',
    statutoryFee: 50,
    professionalFee: 1999,
    gst: 360,
    totalPayable: 2409,
    price: 2409,
    fee: '1999',
    governmentFee: '₹50',
    processingTime: '30-60 days',
    requiredDocuments: ['Death Certificate', 'Family Details', 'Ration Card', 'Property Details'],
    popular: false,
    operationalComplexity: 'high',
  },

  {
    id: 'LEG-005',
    slug: 'succession-certificate',
    name: 'Succession Certificate',
    description: 'Court succession certificate for movable property. Note: Multiple court visits required.',
    category: 'legal',
    categoryGroup: 'Legal Services',
    statutoryFee: 5000,
    professionalFee: 14999,
    gst: 2700,
    totalPayable: 22699,
    price: 22699,
    fee: '14999',
    governmentFee: '₹5,000+',
    processingTime: '180-365 days',
    requiredDocuments: ['Death Certificate', 'Legal Heir Certificate', 'Property Details', 'NOC from Heirs'],
    popular: false,
    isStatutoryFeeVariable: true,
    statutoryFeeNote: 'Court fees vary from ₹5,000 to ₹50,000 based on estate value.',
    operationalComplexity: 'high',
  },

  // ========================================
  // SAFETY & COMPLIANCE (3 Services)
  // ========================================

  {
    id: 'SAF-001',
    slug: 'fire-safety-certificate',
    name: 'Fire Safety Certificate',
    description: 'Fire department safety certificate with inspection. Note: Site visit required.',
    category: 'safety',
    categoryGroup: 'Safety & Compliance',
    statutoryFee: 15,
    professionalFee: 4985,
    gst: 897.30,
    totalPayable: 5897.30,
    price: 5897.30,
    fee: '4985',
    governmentFee: '₹15',
    processingTime: '45-60 days',
    requiredDocuments: ['Building Plan', 'Fire Equipment Details', 'Site Plan', 'Trade License'],
    popular: true,
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  {
    id: 'SAF-002',
    slug: 'pollution-control-noc',
    name: 'Pollution Control NOC',
    description: 'Pollution board clearance with site inspection. Note: Inspector visit required.',
    category: 'safety',
    categoryGroup: 'Safety & Compliance',
    statutoryFee: 5000,
    professionalFee: 9999,
    gst: 1800,
    totalPayable: 16799,
    price: 16799,
    fee: '9999',
    governmentFee: '₹5,000',
    processingTime: '60-90 days',
    requiredDocuments: ['Industry Details', 'Waste Management Plan', 'Emission Details', 'Building Plan'],
    popular: false,
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  {
    id: 'SAF-003',
    slug: 'environmental-clearance',
    name: 'Environmental Clearance',
    description: 'MoEF clearance for large projects. Note: EIA study and inspection required.',
    category: 'safety',
    categoryGroup: 'Safety & Compliance',
    statutoryFee: 0,
    professionalFee: 49999,
    gst: 9000,
    totalPayable: 58999,
    price: 58999,
    fee: '49999',
    governmentFee: '₹50,000 - ₹10,00,000',
    processingTime: '180-365 days',
    requiredDocuments: ['Project Report', 'EIA Study', 'Public Hearing Details', 'Land Documents', 'NOCs'],
    popular: false,
    isStatutoryFeeVariable: true,
    statutoryFeeNote: 'Government fees vary from ₹50,000 to ₹10,00,000 based on project size and category.',
    requiresSiteInspection: true,
    operationalComplexity: 'high',
  },

  // ========================================
  // EDUCATION (4 Services)
  // ========================================

  {
    id: 'EDU-001',
    slug: 'inter-caste-marriage-certificate',
    name: 'Inter-Caste Marriage Certificate',
    description: 'Certificate for inter-caste marriage benefits. Note: Joint presence required for registration.',
    category: 'education',
    categoryGroup: 'Educational Services',
    statutoryFee: 0,
    professionalFee: 999,
    gst: 179.82,
    totalPayable: 1178.82,
    price: 1178.82,
    fee: '999',
    governmentFee: 'Free',
    processingTime: '30-60 days',
    requiredDocuments: ['Marriage Certificate', 'Caste Certificates', 'Joint Affidavit', 'Photos', 'IDs'],
    popular: false,
    requiresPhysicalPresence: true,
    operationalComplexity: 'medium',
  },

  {
    id: 'EDU-002',
    slug: 'degree-certificate-verification',
    name: 'Degree Certificate Verification',
    description: 'University degree certificate verification and attestation.',
    category: 'education',
    categoryGroup: 'Educational Services',
    statutoryFee: 100,
    professionalFee: 799,
    gst: 143.82,
    totalPayable: 1042.82,
    price: 1042.82,
    fee: '799',
    governmentFee: '₹100',
    processingTime: '15-30 days',
    requiredDocuments: ['Original Degree', 'Mark Sheets', 'ID Proof', 'Purpose Letter'],
    popular: false,
    isFullyOnline: false,
    operationalComplexity: 'medium',
  },

  {
    id: 'EDU-003',
    slug: 'school-admission-support',
    name: 'School Admission Support',
    description: 'Assistance with school admission procedures and documentation.',
    category: 'education',
    categoryGroup: 'Educational Services',
    statutoryFee: 0,
    professionalFee: 699,
    gst: 125.82,
    totalPayable: 824.82,
    price: 824.82,
    fee: '699',
    governmentFee: 'Free',
    processingTime: '7-15 days',
    requiredDocuments: ['Birth Certificate', 'Transfer Certificate', 'Mark Sheets', 'Address Proof', 'Caste Certificate'],
    popular: false,
    isFullyOnline: false,
    operationalComplexity: 'low',
  },

  {
    id: 'EDU-004',
    slug: 'disability-certificate-medical',
    name: 'Differently Abled Certificate',
    description: 'Medical board disability certificate. Note: Medical board examination required.',
    category: 'education',
    categoryGroup: 'Educational Services',
    statutoryFee: 0,
    professionalFee: 799,
    gst: 143.82,
    totalPayable: 942.82,
    price: 942.82,
    fee: '799',
    governmentFee: 'Free',
    processingTime: '30-60 days',
    requiredDocuments: ['Medical Reports', 'Aadhaar', 'Photos', 'Doctor Referral'],
    popular: false,
    requiresPhysicalPresence: true,
    operationalComplexity: 'high',
  },

  // ========================================
  // PERSONAL & CIVIC (1 Service)
  // ========================================

  {
    id: 'PCD-101',
    slug: 'marriage-certificate',
    name: 'Marriage Certificate',
    description: 'Official marriage registration certificate. Note: Joint presence required for registration.',
    category: 'personal',
    categoryGroup: 'Personal & Civic Documents',
    statutoryFee: 100,
    professionalFee: 799,
    gst: 143.82,
    totalPayable: 1042.82,
    price: 1042.82,
    fee: '799',
    governmentFee: '₹100',
    processingTime: '15-30 days',
    requiredDocuments: ['Marriage Invitation', 'Photos', 'IDs of Couple', 'Witness Details', 'Address Proof'],
    popular: true,
    requiresPhysicalPresence: true,
    operationalComplexity: 'medium',
  },
];

// Helper functions remain unchanged
export function getServiceBySlug(slug: string): Service | undefined {
  return SERVICES.find((service) => service.slug === slug);
}

export function getServicesByCategory(category: string): Service[] {
  return SERVICES.filter((service) => service.category === category);
}

export function getServicesByGroup(group: string): Service[] {
  return SERVICES.filter((service) => service.categoryGroup === group);
}

export function getPopularServices(): Service[] {
  return SERVICES.filter((service) => service.popular === true);
}

export function getAllServices(): Service[] {
  return SERVICES;
}

export function searchServices(query: string): Service[] {
  const lowerQuery = query.toLowerCase();
  return SERVICES.filter(
    (service) =>
      service.name.toLowerCase().includes(lowerQuery) ||
      service.description.toLowerCase().includes(lowerQuery) ||
      service.category.toLowerCase().includes(lowerQuery)
  );
}

// Service category groups
export const serviceGroups = [
  {
    id: 'student-education',
    name: 'Student & Education Solutions',
    description: 'Certificates and documentation for students',
    icon: '🎓',
  },
  {
    id: 'personal-family',
    name: 'Personal & Family Solutions',
    description: 'Family certificates and legal heir documentation',
    icon: '👨‍👩‍👧‍👦',
  },
  {
    id: 'property-asset',
    name: 'Property & Asset Solutions',
    description: 'Land and property documentation services',
    icon: '🏠',
  },
  {
    id: 'business-licensing',
    name: 'Business & Licensing Solutions',
    description: 'Business licenses and NOCs',
    icon: '🏢',
  },
  {
    id: 'social-pension',
    name: 'Social & Pension Schemes',
    description: 'Government welfare and pension schemes',
    icon: '🤝',
  },
];

// Legacy categories for navigation
export const serviceCategories = [
  { id: 'identity', name: 'Identity & Cards', icon: '🪪', description: 'Identity documents' },
  { id: 'certificates', name: 'Certificates', icon: '📜', description: 'All certificates' },
  { id: 'legal', name: 'Legal Services', icon: '⚖️', description: 'Legal documentation' },
  { id: 'business', name: 'Business', icon: '🏢', description: 'Business licenses' },
  { id: 'property', name: 'Property', icon: '🏠', description: 'Property services' },
  { id: 'welfare', name: 'Welfare', icon: '🤝', description: 'Social welfare' },
];

// Form configuration functions
export function getServiceFormFields(slug: string) {
  const config = SERVICE_FORM_CONFIGS[slug];
  
  if (!config) {
    return {
      fields: [
        {
          id: 'fullName',
          name: 'fullName',
          label: 'Full Name',
          type: 'text' as const,
          required: true,
          placeholder: 'Enter your full name',
        },
        {
          id: 'mobileNumber',
          name: 'mobileNumber',
          label: 'Mobile Number',
          type: 'tel' as const,
          required: true,
          placeholder: '10-digit mobile number',
        },
        {
          id: 'email',
          name: 'email',
          label: 'Email Address',
          type: 'email' as const,
          required: false,
          placeholder: 'your.email@example.com',
        },
      ],
      requiredDocuments: [],
    };
  }

  return {
    fields: config.formFields,
    requiredDocuments: config.requiredDocuments,
    complianceNotes: config.complianceNotes,
  };
}